include::{root}/.inc/include.adoc[]

= Lohnsteuer

* 2021 erledigt
* 2022 eingereicht

== Jahresausgleich

* Basisrente 201139069 Dokument im https://www.cosmosdirekt.de/kundenportal/[Portal]
* Dokumente 2022 durchgehen und Regeln finden.


== Lohnsteuer Seminar
* Nebeneinkünfte 410 € pro Jahr ist frei
* Kapitalerträge für die noch keine Abgeltungssteuer entrichtet wurde. Automatisch 25%. Kümmern bei Auslandskonten
* Abgabe einer Steuererklärung Frist 2022 bis 31.07.23, vorher verlängern lassen. 25€ pro Monat Strafe.
* Große Eingriffe besser in einem Jahr komplett machen, mehr als 1200€ in dem Jahr auch bezahlen!
* Kapitalerträge über 825€

== Prinzipiell
* Bestätigung 2022 gezahlte Versicherungs-Beiträge Techniker Krankenkasse
  ** Klären ob schon elektronisch übermittelt
* Lohnsteuerbescheinigung für 2022  / STree Temp Experts GmH
  ** Klären ob schon elektronisch übermittelt
* Haftpflichtversicherungen z. B. Kfz und private Haftpflichtversicherungen (Rechnungen)
  ** Unter huk.de. Für 2023 erledigt.
* Haushaltsnahe Dienstleistungen z. B. Handwerkerleistungen auch Schornsteinfeger (Rechnungen)
  ** Schornsteinfeger: https://home.digibase.com/post_assignments
  ** 2023 erledigt
* Spenden, Geldzuwendungen (Soko Tierschutz € 50 liegt vor)
* Außergewöhnliche Belastungen wie Arztrechnungen etc. (hier liegen bereits Quittungen vor)

