include::{root}/.inc/includeDaily.adoc[]

= 2023-11-30

== Aufgaben 
Themen: G Gesundheit, J Job, F Finanz, P Privat, H Haus

* Use backlog to keep overview in daily work
* link:../prv/backlog.adoc[BackLog]



=== Heute

=== Mittag
=== Abend
=== Sport

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Task Kotlin Entwicklung
* [ ] JDW Bewerben! Plath, bundesdruckerei Maurer, Toni Gansel Zertifikate Jobs,
https://www.bundesdruckerei.de/de/karriere/maurer-electronics-hamburg

* [ ] weiter task printservice einbauen, Testen! Für Encryption


























''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
== Kühne & Nagel
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

=== Do and Done
* WVL Mail: Hat das mit Stundenzettel bei sThree geklappt?

=== Woche Buchen ('.' Log Time)
https://jira.int.kn/secure/Tempo.jspa[MyWork]
https://jira.int.kn/browse/KNOMP-29388[Operationals]
https://jira.int.kn/browse/KNOMP-31487[Remove Status]


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== KNOMP-34983 [unified-model] IllegalArgumentException
* https://jira.int.kn/browse/KNOMP-35253[JIRA]
* link:../.ticket/35253.adoc[Ticket]



''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== KNOMP-34983 [status-tracking] Define APIs and ignored test cases

Hi Dietmar, I have just added deployment hints (h3. Deployment Hints) in the description for
https://jira.int.kn/browse/KNOMP-33392

Please make sure these hints will appear in the table https://esp-release-notes.int.kn/ after the release 6.08 for each of 4 verticals we created PRs for





''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
== Notizen


|===
| Mail Privat |Cal Privat |Müll  |Sport  |Alarm |Buchen
| Mail Custom |Cal Custom |Brief |Chat   |Daily |
|===

