include::{root}/.inc/includeDaily.adoc[]

= 2023-11-27

== Aufgaben 
Themen: G Gesundheit, J Job, F Finanz, P Privat, H Haus

=== Heute


* Sonntag? Start Energiearbeit: 2h Labor, 3 Haufen: (Behalten) Verkaufen Verschenken Entsorgen
* Kaminholz bestellen
* usb kabel
* DKB Konto needed?
* Comdirect? Mail!

* [ ] dW Bewerben



=== Lernen
* Filme von Marcin
* Buch auf Kindle Hands dirty Hexagonal Architektur
* Udemy Lehrgang: https://www.udemy.com/course/microservices-clean-architecture-ddd-saga-outbox-kafka-kubernetes/learn/lecture/31152934?start=195#overview
* PlantUml lernen: Beispiel umsetzen https://app.diagrams.net/#G1Iw_ZB_ynIEq8qsCoXFF1qO54P1H2mqqn
* Beispiel esp-itemm-master anschauen


=== Mittag
=== Abend
=== Sport

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Task Kotlin Entwicklung
* [ ] JDW Bewerben! Plath, bundesdruckerei Maurer, Toni Gansel Zertifikate Jobs,
https://www.bundesdruckerei.de/de/karriere/maurer-electronics-hamburg

* [ ] weiter task printservice einbauen, Testen!


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Eichengrund
* [ ] FdW XX 06 Wertermittlung link:../fnz/eichengrund-uebertragung.adoc[Stand]
* [ ] F w XX 07 Garage leckt link:../fnz/eichengrund-stand.adoc[Stand]
* [ ] Was wir mit den Geldern der OLB? link:../fnz/oberes-juechen-grundstuecke.adoc[Details]


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Weitere, laufende Projekte
* [ ] H W 90 Keller säubern"
* [ ] J W 90 08 link:../prv/entscheidungsfindung-mentale-modelle.adoc[MM]
* [ ] J W 30 08 Orga: Board: Fehlende Tasks anbringen, priorisieren
* [ ] H W 60 Liste jeder Raum 60min, Entsorgen-Verkaufen-Behalten.

* [ ] GdW 30 09 KKasse wechseln
* [ ] JDW 30 03 PlaBewerbung fertig
* [ ] Hdw 30 03 Isomatte (+ Luftbett) auf Dichtigkeit prüfen
* [ ] F W 30 03 SThree Monatsnachweise einsortieren und drucken
* [ ] JdW 60 03 Office: Script in kh: Copy smb; ocr +  guess Name! Enum mit bekannten Absendern
* [ ] Regalwand Stube Kleinanzeigen suchen


== Backlog

=== Irgendwann
* [ ] Hdw 30 03 Isomatte (+ Luftbett) auf Dichtigkeit prüfen
* [ ] Gdw TB 01 Harte Matratze im eigenen Haus oder kaufen.
* [ ] Gw  60 03 Skript, wie man das Wissen und Dateinamen aus doc & office grepfähig machen kann, vielleicht mit t d <search> (oder o)
* [ ] Jdw 99 03 Mein Miro https://miro.com/app/board/o9J_lruDyUo=/ umziehen nach board.drawio.svg  ?Daraus OKRs generieren? 3, 5, 15 Jahres Plan?

* [ ] FDW 30 03 ?Jens Rabe monatlich https://aktienkannjeder.de/?utm_source=mail&utm_medium=newsletter&utm_campaign=aktienkannjeder
* [R] F W 99 01 Andree de B Aufstellung verstehen, Pflege-Routine erarbeiten
* [ ] F W 45 03 Outcome Frame Dietmar Vermietet. Vorteile beachten.
* [ ] Fdw 99 03 Amazon Invoice Generator, alles absetzbar und nicht verfolgbar. Einarbeitung PDF Generator

* [ ] P w 30 03 CM Notizen auswerten,
* [R] P w 99 03 Alle Methoden von CM zusammenfassen  und besser strukturieren als adoc wenn möglich.
* [ ] P   60 03 CM 7 Schritte fertig

* [ ] H W TB 01 Keller aufräumen




















''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
== Kühne & Nagel
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

=== Do and Done
* WVL Mail: Hat das mit Stundenzettel bei sThree geklappt?

=== Woche Buchen ('.' Log Time)
https://jira.int.kn/secure/Tempo.jspa[MyWork]
https://jira.int.kn/browse/KNOMP-29388[Operationals]
https://jira.int.kn/browse/KNOMP-31487[Remove Status]


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== KNOMP-34983 [unified-model] IllegalArgumentException
* https://jira.int.kn/browse/KNOMP-35253[JIRA]
* link:../.ticket/35253.adoc[Ticket]



''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== KNOMP-34983 [status-tracking] Define APIs and ignored test cases

Hi Dietmar, I have just added deployment hints (h3. Deployment Hints) in the description for
https://jira.int.kn/browse/KNOMP-33392

Please make sure these hints will appear in the table https://esp-release-notes.int.kn/ after the release 6.08 for each of 4 verticals we created PRs for





''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
== Notizen


|===
| Mail Privat |Cal Privat |Müll  |Sport  |Alarm |Buchen
| Mail Custom |Cal Custom |Brief |Chat   |Daily |
|===

