include::{root}/.inc/includeDaily.adoc[]

= 2023-12-28

== Aufgaben 
Themen: G Gesundheit, J Job, F Finanz, P Privat, H Haus

* Use backlog to keep overview in daily work
* link:../prv/backlog.adoc[BackLog]



=== Kleinkram
* [ ] FDW 30 12 800€ Entnehmen
* [ ] JDW 30 12 Freelancer map, Börsen updaten!
* [ ] JDW 30 12 Profil updaten, recruiter informieren Anüler, FreiB & Fest
* [ ] F   30 12 KKasse wechseln
* [ ] P   60 12 Bücher aussortieren und zurück schicken
* [ ] F   30 12 OLB anrufen, wiederanlage Mündelsicher
* [ ] H   30 12 Ladestecker bauen -> PausenJob


=== Heute
* [ ] Jdw 60 12 Plan erstellen!
* [ ] FDW 60 12 Cosmos direkt abarbeiten

* [ ] Pdw 30 12 Zeichnungen: Stube Regal, Gewürzregal, Vogeltränke -> ebayKA suchen

* [ ] Jdw 99 12 Projekt Wecker / Uhr Website starten
  ** Vue, Spring-boot


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== CMD Tool Task
* [ ] weiter task printservice einbauen, Testen! Für Encryption


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Eichengrund






























''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
== Neue Firma
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== JIRA-12345 Titel
* https://jira/JIRA-12345[JIRA]
* link:../.ticket/12345.adoc[Ticket]



''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
== Notizen


|===
| Mail Privat |Cal Privat |Müll  |Sport  |Alarm |Buchen
| Mail Custom |Cal Custom |Brief |Chat   |Daily |
|===

