include::{root}/.inc/includeDaily.adoc[]

= 2023-04-18

== Aufgaben 

=== Morgen
* [ ] BKK überweisen
* [ ] PlaBewerbung fertig


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== KNOMP-31571 Define deletion contracts
* https://jira.int.kn/browse/KNOMP-31487[Epic]
* https://jira.int.kn/browse/KNOMP-31571[Ticket]
* https://jira.int.kn/browse/KNOMP-31535[Delete]
* https://jira.int.kn/browse/KNOMP-31533[List]
* https://wiki.int.kn/display/GSD/Remove+Shipment+or+Container+Status[wiki]



Shipment
  (Shipment.OBNumber + Tms_Status.Type) -> Tms_status.ID
  (Shipment.OBNumber + Tms_Status.Type) -> ESP_SHIPMENT_MILESTONE.ID
Container
  (Shipment.OBNumber + Container.Container_number) -> Container_Event.ID
  (Shipment.OBNumber + Container.Container_number) -> Esp_Container_Event.ID




''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== KNOMP-30858 [oedi-data-bridge] KN Order Management Portal
PreShipmentSender
  61 Proxy muss noch angepasst werden, hat keine routing keys für myKn, gibt endpunkte noch nicht.
  35 send() mapping fehlt, counter? der Soll synchron sein. Aus der Eventhistorie zählen, wie viele das sind.
  206 USBucketConsumerInterTest.

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== 30061 Unlink FCL shipment
link:../.cus/.kn/.ticket/30061.adoc[docu]
https://jira.int.kn/browse/KNOMP-30061[jira]

* [ ] Erkenntnis: Sea wird nicht ge-canceled, kein Relinkage. Irgendwie dokumentieren?
* [ ] Wie ist die Verbindung
* [ ] Sven docu in link:../kn/esp-scaling-support.adoc[] zeigen

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''




























* [ ] Bei der Stadt Esens anrufen. Erstmal selber lesen wie das zusammen hängt
* [ ] JDW 60 Script in kh: Copy smb; ocr; guess Name
----
Eine andere Option ist das Tool "PDF Rename", das auf der Linux-Befehlszeile verwendet werden kann. Es ermöglicht Ihnen, den Dateinamen eines PDF-Dokuments auf der Grundlage des Datums und des Betreffs des Dokuments zu ändern. Hier sind die Schritte:

Installieren Sie das Tool "PDF Rename" auf Ihrem Linux-System. Sie können dies in der Regel über den Paketmanager Ihrer Linux-Distribution tun, zum Beispiel mit dem Befehl "sudo apt install pdfrename" für Ubuntu.

Navigieren Sie mit dem Befehl "cd" zu dem Verzeichnis, in dem sich das gescannte Dokument befindet.

Geben Sie den Befehl "pdfrename -f '%y%m%d_%t.pdf' -t" ein, um den Dateinamen des Dokuments zu ändern. Der Befehl nutzt das Datum des Dokuments als ersten Teil des Dateinamens im Format "YYMMDD" und den Betreff als zweiten Teil des Dateinamens. Beachten Sie, dass Sie möglicherweise den Befehl an Ihre spezifischen Anforderungen anpassen müssen.

Diese beiden Tools sind nur Beispiele, es gibt auch andere OCR-Software-Tools und Tools zur PDF-Dateibenennung, die Sie ausprobieren können, um den Dateinamen eines PDF-Scans automatisch zu generieren.
----



* Wochenroutine definieren
  ** Posteingang, Amazon, Papierablage. Alles einmal als Papier
  ** Ziel: LSJAusgleich schnell, Rente übersicht was wann erhalten, Vermögensstand übersicht

== Idle
* [ ] JDW 30 Zoom Webinar aufzeichnen

* [ ] JDW 30 SMART zur Liquidation erstellen.
* [ ] JDW 60 Plath Schreiben!


* [ ] Jw  60 Eigene Q mit mehreren Topics
* [ ] State-Diagram zeichnen, mit Events als Vorbereitung für https://jira.int.kn/browse/KNOMP-31118[jira]


* [ ] Document tms-export branch KNOMP-22972

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
== Private Aufgaben
Die Tue-Nicht-gut-Falle!
State: ' ' Todo, B = Blocked, X = Done, R = Refine, W = Wiedervorlage
Themen: G Gesundheit, J Job, F Finanz, P Privat, H Housekeeping
Eisenhauer: D=sehr dringend  W=sehr wichtig
Dauer in [min], 99 = Fehlende Subtask!, TB= Time box
Start Monat

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

== Backlog

=== Shortrunner
* [-] FDW 15 WVL start 23.03. FA Briefe an Bahlburg mailen
* [ ] GDW 15 Athletikum starten
  ** https://www.tk.de/techniker/gesundheit-und-medizin/behandlungen-und-medizin/sportmedizin-und-sportverletzungen/sportmedizinische-sportorthopaedische-behandlung-hamburg-2129924
  ** 040/7410-58559, Athletikum direkt: 040/7410-28540
* [B] Fdw 15 03 Krankenkasse wechseln nach Athletikum 450€ max pro Jahr sparen

=== Longrunner
* [ ] GDw 99 03 Encryption fertig machen, mergen!
* [ ] GDw 30 03 cloud prv body und prv sport mergen. Es fehlt ein health oder ges Ordner in doc
* [ ] Gdw TB 01 OtF harte Matratze
* [ ] Gw  60 03 Skript, wie man das Wissen und Dateinamen aus doc grepfähig machen kann, vielleicht mit t d <search>
* [ ] Gw  60 03 Ongoing: t minimalismus

* [ ] JDW 60 03 Outcome frame mit Plath, Plath oder nicht? Worauf 100% Focus?(elo?, FE?)
* [ ] JDw 60 03 Handy Lösung
* [ ] Jdw 99 03 Mein Miro https://miro.com/app/board/o9J_lruDyUo=/ umziehen nach board.drawio.svg  ?Daraus OKRs generieren? 3, 5, 15 Jahres Plan?
* [ ] J   60 03 Skripte in kh lassen, alle configs nach vault oder?

* [W] FDW 30 03 Lohnsteuer Jahresausgleich fertig fertig. Evaluieren von Software.  Welche Fragen an Fr. Bahlburg? Status QCC?
* [ ] FDW 60 01 Depot 7988387 kündigen, brauche ich da Hilfe, Frage an Frau Bahlburg?
* [ ] FDW 30 03 ?Jens Rabe monatlich https://aktienkannjeder.de/?utm_source=mail&utm_medium=newsletter&utm_campaign=aktienkannjeder
* [R] FW  99 01 Andree de B Aufstellung verstehen.
* [ ] FW  15 03 Eigene Rentendokumentation sichern in SV
* [ ] FW  45 03 Outcome Frame Dietmar Vermietet
* [ ] Fdw 99 03 Amazon Invoice Generator, alles absetzbar und nicht verfolgbar. Einarbeitung PDF Generator
* [ ] Fdw 00 03 ?Dokumenten scanner kaufen?  Vorarbeit: Was genau bringt der Aufwand, alle Aktendokumente digital zu haben? Welchen strategischen Vorteil? t digital anlegen
* [X] FW  15 03 Klärung Weide? Reents Immobilien 0174 1616464 anrufen, was ist letzter Stand? Kann er helfen beim verpachten?
* [ ] Fw  60 01 Schreibtisch frei

* [ ] Pw  30 03 CM Notizen auswerten,
* [R] Pw  99 03 Alle Methoden von CM zusammenfassen  und besser strukturieren als adoc wenn möglich. Anderes ebook?
* [ ] Pw  30 03 Meinen Film anschauen, was bewirkt es?
* [ ] P   60 03 CM 7 Schritte fertig

* [W] HDW 10 03 Heizung leckt, Bohlmann anrufen
* [ ] HW  TB 01 Keller aufräumen
* [ ] H   30 03 Isomatte (+ Luftbett) auf Dichtigkeit prüfen


== Notizen


|===
| Mail Privat |Cal Privat |Müll  |Sport  |Alarm |Buchen
| Mail Custom |Cal Custom |Brief |Chat   |Daily |
|===

