include::{root}/.inc/includeDaily.adoc[]

= 2023-08-21

== Aufgaben 
* Bau mal eine ultraleichten Ring-Trainer mit Aramidschnur und Prusik für unterwegs



* [ ] FdW 10 08 EigrÜ: WVL 18.08 11:00 Raveling anrufen, fehlen noch daten?
* [ ] JDW 30 08 Orga: Board: Fehlende Tasks anbringen, priorisieren

=== Woche Buchen ('.' Log Time)
https://jira.int.kn/secure/Tempo.jspa[MyWork]
https://jira.int.kn/browse/KNOMP-29388[Operationals]
https://jira.int.kn/browse/KNOMP-31487[Remove Status]


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== KNOMP-33720 [DI] [esp-shared-message-api] add "Shipper's Reference" to booking event message
* https://jira.int.kn/browse/KNOMP-33720[Jira]

[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  20.180 s
[INFO] Finished at: 2023-08-21T16:08:43Z
[INFO] ------------------------------------------------------------------------
$ RELEASE_VERSION=${module}-$(cat $CI_PROJECT_DIR/version.txt)
$ git tag -a $RELEASE_VERSION -m "release tag"
$ python3 esp-release-notes/scripts/generate-release-notes.py --commit "Release Notes for ${CI_PROJECT_NAME}-$RELEASE_VERSION"
Traceback (most recent call last):
File "/builds/kn-esp/esp-shared-message-api/esp-release-notes/scripts/generate-release-notes.py", line 298, in <module>
mode is 'current' commit:Release Notes for esp-shared-message-api-booking-event-message-2.16.1
processing project...
esp-shared-message-api - booking-event-message-2.16.1
previous tag is None
No togglz found
Found 464 commits for range HEAD
main()
File "/builds/kn-esp/esp-shared-message-api/esp-release-notes/scripts/generate-release-notes.py", line 275, in main
write_release_notes(skip_existing=args.skip_existing,
File "/builds/kn-esp/esp-shared-message-api/esp-release-notes/scripts/generate-release-notes.py", line 232, in write_release_notes
jira_tickets = fetch_ticket_info_from_jira(ticket_keys)
File "/builds/kn-esp/esp-shared-message-api/esp-release-notes/scripts/jira.py", line 109, in fetch_ticket_info_from_jira
tickets = __get_jira_tickets(ticket_keys)
File "/builds/kn-esp/esp-shared-message-api/esp-release-notes/scripts/jira.py", line 116, in __get_jira_tickets
json_string = __get_json_string_from_jira(ticket_keys)
File "/builds/kn-esp/esp-shared-message-api/esp-release-notes/scripts/jira.py", line 147, in __get_json_string_from_jira
return fetch_content_from_url_as_string(
File "/builds/kn-esp/esp-shared-message-api/esp-release-notes/scripts/commons.py", line 24, in fetch_content_from_url_as_string
with urllib.request.urlopen(req) as response:
File "/usr/lib64/python3.9/urllib/request.py", line 214, in urlopen
return opener.open(url, data, timeout)
File "/usr/lib64/python3.9/urllib/request.py", line 517, in open
response = self._open(req, data)
File "/usr/lib64/python3.9/urllib/request.py", line 534, in _open
result = self._call_chain(self.handle_open, protocol, protocol +
File "/usr/lib64/python3.9/urllib/request.py", line 494, in _call_chain
result = func(*args)
File "/usr/lib64/python3.9/urllib/request.py", line 1389, in https_open
return self.do_open(http.client.HTTPSConnection, req,
File "/usr/lib64/python3.9/urllib/request.py", line 1350, in do_open
r = h.getresponse()
File "/usr/lib64/python3.9/http/client.py", line 1377, in getresponse
response.begin()
File "/usr/lib64/python3.9/http/client.py", line 320, in begin
version, status, reason = self._read_status()
File "/usr/lib64/python3.9/http/client.py", line 281, in _read_status
line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
File "/usr/lib64/python3.9/socket.py", line 704, in readinto
return self._sock.recv_into(b)
File "/usr/lib64/python3.9/ssl.py", line 1242, in recv_into
return self.read(nbytes, buffer)
File "/usr/lib64/python3.9/ssl.py", line 1100, in read
return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 1

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== KNOMP-32333 [esp-mykn-components] fix local development process
* https://jira.int.kn/browse/KNOMP-32333[Jira]
link:../.cus/.kn/.ticket/32333.adoc[Ticket]

* [X] Doku: Nutzung Local & Integration + Docker Testdata import
* [X] Fix: URL correction local docker environment




''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
































=== Eichengrund
* [ ] KKasse wechseln
* [ ] link:../org/bachelor-of-time-tim-reichel.adoc[Frog]


* [ ] t projekte files mergen. GästeWC, Hutablage


* [ ] Wertfeststellung per Ertragswertverfahren
* [ ] Feststellung Kosten Renovierungsstau nur der Pflichtanteile (Heizung!)
* [ ] Besichtigungstermin mit Gutachter mit beiden Mieterinnen.
* [ ] Kontoauszüge für Mieteinnahmen

* [ ] WVL: 29.06. auf 04.07 Stb Janssen Middels letzten 3 EKStErklärungen, Betr. u. Heizkosten, Welcher Steuersatz -> Was bleibt netto von der Miete?

* [ ] WVL: v14. auf 16.06. Mail Preuss   -> Was zahle ich drauf
* [ ] WVL: v14. auf 16.06. Mail Raveling -> Diverse Fragen, Frage Wilfried Goldenstein
* [ ] WVL: v14. auf 17.06. Rückruf Valerie -> Steuern.
* [ ] WVL: v14. auf 16.06. Mail Schapp   -> Änderungswünsche
* [ ] WVL: v14. auf 17.06. WhAp Reents   -> Wiese?







=== WIP
* [ ] JDW 30 PlaBewerbung fertig


==== Backlog nach Prio
* [ ] Fdw 30 06 Steuer 2021 Quittungen durchgehen, nach prinzipiellen Unterlagen und diese dokumentieren
* [ ] Hdw 30 03 Isomatte (+ Luftbett) auf Dichtigkeit prüfen

* [ ] F W 30 SThree Monatsnachweise einsortieren und drucken

* [ ] JdW 60 Office: Script in kh: Copy smb; ocr +  guess Name! Enum mit bekannten Absendern
* [ ] F W 30 WVL OLB Tan verfahren.evt Kündigen auf Haspa gehen? Kosten evaluieren



== KN Idle
* [ ] JDW 30 03 Zoom Webinar aufzeichnen, als unkonkrete Investition
* [ ] Jw  60 03 Eigene Q mit mehreren Topics
* [ ] Jdw 30 04 State-Diagram zeichnen, mit Events als Vorbereitung für https://jira.int.kn/browse/KNOMP-31118[jira]
* [ ] Jdw 30 03 Document tms-export branch KNOMP-22972

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

== Backlog

=== Dringender
* [ ] GDW Vorsorge Terminserien anlegen

=== Irgendwann
* [ ] Gdw TB 01 OtF harte Matratze
* [ ] Gw  60 03 Skript, wie man das Wissen und Dateinamen aus doc & office grepfähig machen kann, vielleicht mit t d <search> (oder o)
* [ ] Jdw 99 03 Mein Miro https://miro.com/app/board/o9J_lruDyUo=/ umziehen nach board.drawio.svg  ?Daraus OKRs generieren? 3, 5, 15 Jahres Plan?

* [W] FDW 30 03 Lohnsteuer Jahresausgleich fertig fertig. Evaluieren von Software.  Welche Fragen an Fr. Bahlburg? Status QCC?
* [ ] FDW 60 01 Depot 7988387 kündigen, brauche ich da Hilfe, Frage an Frau Bahlburg?
* [ ] FDW 30 03 ?Jens Rabe monatlich https://aktienkannjeder.de/?utm_source=mail&utm_medium=newsletter&utm_campaign=aktienkannjeder
* [R] F W 99 01 Andree de B Aufstellung verstehen.
* [ ] F W 45 03 Outcome Frame Dietmar Vermietet
* [ ] Fdw 99 03 Amazon Invoice Generator, alles absetzbar und nicht verfolgbar. Einarbeitung PDF Generator

* [ ] P w 30 03 CM Notizen auswerten,
* [R] P w 99 03 Alle Methoden von CM zusammenfassen  und besser strukturieren als adoc wenn möglich.
* [ ] P   60 03 CM 7 Schritte fertig

* [ ] H W TB 01 Keller aufräumen




== Notizen


|===
| Mail Privat |Cal Privat |Müll  |Sport  |Alarm |Buchen
| Mail Custom |Cal Custom |Brief |Chat   |Daily |
|===

