include::{root}/.inc/includeDaily.adoc[]

= Freitag, 26. Juli 2024

link:../fnz/office.adoc[Regeln]

== Aufgaben
State: ' ' Unplanned, B = Blocked, X = Done, R = Refine it!, W = Wiedervorlage, S = Selected
Themen: G Gesundheit, J Job, F Finanz, P Privat, H Haus, O Orga, M Minimalismus
Task: SUp: Standup, Cur: Current




== HEUTE ###############################################################################################################

link:../hms/hermes-übung.adoc[Üben]




=== Infrasturktur
* [ ] VPN und OneDrive installieren, zum Sync der pps.kdb
* [ ] Intellij Lizens auf Hermes umstellen
* Zugang zu google cloud prüfen
* Passwörter aus browsers üpbertragen
* Tobias Welther kontaktieren, vorstellen

== Daily ###############################################################################################################


----
Pilot: 2.18.2
Bundesweit: 2.17.0
2.18.2 Kaputt: Rollback -> retag 2.17.0 auf 2.18.3
2.18.3 (auf Basis 2.17.0) kommt mit den nuen Datwedgeprofilen nicht zurecht
2.18.4 (auf Basis 2.17.0)-> kommt mit neuen  Datawedgeprofilen zurecht
2.18.4 (auf Basis 2.17.0) -> kommt nicht mehr mit altem Profil zurecht => Bundesweite 2.17.0 kann nicht upgedated werden
WIr benötigen 2.18.5 auf Basis 2.17.0 die sowohl mit neuem als auch altem Datawedge-Profil zurecht kommt
----

=== Was habe ich gemacht
* AM Column Filter: Umgang mit Null Werten, Join statt select, Alphabetische Sortierung,
* [ ] Jonas: Was ist mit Jira Ticke: Version Rollback Task angelegt PPS-1164
* Learnings des Setups in Readmes gießen

=== Woran arbeite ich gerade
* Learnings des Setups in Readmes gießen und pushen

=== Was sollte ich tun:

Montag:
MA mergen! Extraf fliegt weg vom intent
Nav vereinfacht
wenn du direkt zum launcher kannst must du dich trotzdem verfizieren mit ausweis



* Reviews!
* [ ] am tests und pipeline reparieren
* [ ] Support-Fähig ab September (von Jan)
* [ ] AWS GCP Account Prüfen
* [ ] Lern Release und Deploy. Releasebranch sollte nur 2 Nummern haben also 3.2 oder 3.2.xx
* [ ] 23.08 Aufwände für Android 14


=== Was werde ich tun
* [ ] Column Filter Tests schreiben
* DIRD Doku in jira updaten


=== Wo brauche ich Hilfe
* [ ] Ob das in Ordnung ist: Ticket einlösen für codetalk
* [ ] Ops Genie, zusammen mit EZSB?
* [ ] Überstunden planen in VTag in Interflex



=== Später
* [ ] SDK Man installieren
* [ ] Brauche Win10 Test für Docker extra_hosts (mac-api)



''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== PPS-1108 Kommentarfeld für User
* https://hermesgermany.atlassian.net/browse/PPS-1108[jira]
* link:../.ticket/1108.adoc[Notes]
* [ ] API: ScheduledTasksService Uhrzeiten auseinander ziehen, sinnvoller gestalten
* [ ] Soll in die 3.14 rein


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== PPS-1164 Rollbackversion erstellen
* https://hermesgermany.atlassian.net/browse/PPS-1164[jira]


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== PPS-1152 DIRD
* https://hermesgermany.atlassian.net/browse/PPS-1152[jira]
* link:../.ticket/1152.adoc[Notes]
* O--o Doku sammeln


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== PPS-1123 [Nicht technisch] Onboarding Dietmar
* https://hermesgermany.atlassian.net/browse/PPS-1123[Jira]
* [ ] Login Einführung AWS
* [ ] Login Einführung GCP
* [ ] Soti und SmartIT Einführung mit Mofid





==  ####################################################################################################################
==  #####################################################################################################################
==  #####################################################################################################################

* Holz dreieck bauen für Schreibtisch
* WVL Rav anrufen
* Mit Andrea Urlaub planen
* Fliegengitter bestelle, 7 Pläne machen mit zeichnung und masse und Bestellung der Teile

* [ ] Brandkasse fragen, warum nur 25.000

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Eichengrund
* link:../fnz/immo/eichengrund-haus.adoc[]

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Gesundheit
* [ ] F-- 30 < ? > KKasse wechseln

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Haus
* [ ] H-- 30 < ? > Ladestecker bauen -> PausenJob
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

== Notizen

|===
| Mail Privat |Cal Privat |Müll  |Sport  |Alarm |Buchen
| Mail Custom |Cal Custom |Brief |Chat   |Daily |
|===