include::{root}/.inc/includeDaily.adoc[]

= Donnerstag, 29. Februar 2024

link:../def/score-board.adoc[Daily Score Board]

== Aufgaben
Themen: G Gesundheit, J Job, F Finanz, P Privat, H Haus, O Orga

* Use backlog to keep overview in daily work
* link:../prv/backlog.adoc[BackLog]
* [ ] Paper Score board?



== Abrechnung Marokko

* Einzel
  ** Zusammen 26€ Sprit Friedrichkoog
  ** Dietmar 35 Taxi Flughafen Hamburg
  ** Dietmar 30 Taxi Flughafen agadir (300Dirham)
  ** Nur Andrea: Holafly eSim 37€, 25€ Tasche,
  ** Nur Dietmar: Bodyboard 5€, Lampe 7€

* Kreditkarte
  ** 17.02: MELLOULOUL  100,10€
  ** 18.02: MARRAKECH    97,80€
  ** 19.02: OUARZAZATE  199,12€
  ** 24.02: Agadir      192,06€
  ** 26.02: Restgeld    -80,00€
  ** Summe Kreditkarte  509,08€


Andrea eSim Holafy     37,00€
Andrea Tasche          25,00€
Anteil Sprit F.koog    13,00€
Anteil Taxi Hamburg    17,50€
Anteil Taxi Agadir     15,00€
Anteil D-Einkäufe      -6,00€
Anteil Kreditkarte:   254,54€

Summe                 356,04€







* Gedanken
** Apfelessig zum Abnehmen, 0% Zucker
** yubikee fertig

* Steuer
* Abrechnung Marokko
* Briane Greene der Stoff aus dem der kosmos ist
* Backup Strategie


== Heute: (Ziel immer W)


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Eichengrund Übertragungsvertrag
link:../fnz/immo/eichengrund-uebertragung.adoc[Stand]
* [ ] Findeklee zusammenfassung durchlesen
* [ ] Termin zur Beurkundung mit Frau Schlüchting unter 04941/92366-15 absprechen

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== OLB OberesJüchen Anlage
* [W] Frau Reents von der OLB fragt nochmal nach, welche Möglichkeiten es gibt.

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Gesundheit
* [ ] G W 30 < ? > 29.01 Urologe besuchen, Zettel + m. gefüllter Blase Mo-Fr 8:30 - 11:00 Mo-Do 15:00 - 18:00.
* [ ] F   30 < ? > KKasse wechseln

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Eichengrund Schimmel
* [W] Fdw 10 < ? > 09.02 HR, war der Test bei seiner Immobilie erfolgreich?


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Haus
* [ ] H   30 < ? > Ladestecker bauen -> PausenJob
* [ ] Hdw 60 < ? > Stromfresser finden, was ist mir son Server wert.

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Lernen
* [ ] Jdw 99 < ? > Projekt Wecker / Uhr Website starten
  ** Angular, spring boot
* [ ] Udemy Kurs DDD ist echt gut!

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
== Notizen


|===
| Mail Privat |Cal Privat |Müll  |Sport  |Alarm |Buchen
| Mail Custom |Cal Custom |Brief |Chat   |Daily |
|===

