include::{root}/.inc/includeDaily.adoc[]

= Freitag, 28. Juni 2024

link:../fnz/office.adoc[Regeln]
link:../def/score-board.adoc[Daily Score Board]

== Done
* 07:00 - 09:00
* 09:00 - 11:00
* 11:00 - 13:00
* 13:00 - 15:00
* 15:00 - 17:00

== Aufgaben
State: ' ' Unplanned, B = Blocked, X = Done, R = Refine it!, W = Wiedervorlage, S = Selected
Themen: G Gesundheit, J Job, F Finanz, P Privat, H Haus, O Orga, M Minimalismus


== Gestern ##############################################################################################################
* [x] SIT System integration Test
* 1121 Lösungsmöglichkeiten gesucht


//       ###############################################################################################################
== HEUTE ###############################################################################################################
* Confluence Admin rausfinden -> Ticket erstellen lassen über Support
* Was ist masterplan? Login funktioneirt nicht


* [x] Docker ? Compose einrichten
* [ ] VPN installieren



Dealer App? WLAN Zertificat

* Mail
  ** [ ] Raveling Anzeige finden im Netz
* Ewe Netz mailen Eigentümer klären
* OOVW mailen Eigentümer



* [ ] Vermögenswirksame Leistungen, Endgeldumwandlung, an HR melden. Direkt brutto
* [ ] HR: Direktversicherung
* [ ] Rexx Deutschlandticket
* [ ] JobRad? Vollkasko zahlt hermes
* [ ] Genussrechte?



== Frog FIRST!!!
// ---------------------------------------------------------------------------------------------------------------------
8:30 15:30 fri buchen

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== PPS-1121 MAC Doku im Confluence ablegen
* https://hermesgermany.atlassian.net/browse/PPS-1121[jira]
* mac-api/arch mac-ui/arch
* https://github.com/mihaeu/cosmere

abc

* Lösungsmöglichkeiten
  ** In confluence: Abtippen ODER Generieren & Pasten ODER Build-Pipeline
  ** Ablage auf externen Server z.B. mac-ui?

* [ ] Bettina Funk sagt: Stefan Stapel, Katja Haase (WVL!) Technischen User beantragen!
  ** danach Bettina dann nochmal bescheid geben, damit der berechtigt wird.
* Das Pipeline Skript anpassen!

* t encrpytion reparieren nach drive document


`find . -name '*.md' | sed 's/.md//' | xargs -i pandoc -f gfm -w jira {}.md -o {}.jira`
https://www.youtube.com/watch?v=5o1GRFdKUCE[YT]
 ~/project/sandbox/poc-sync-markdown-with-confluence



https://gist.github.com/mkweskin/e531e65791c1d8036dd720ef3baf8af6[Confluence editing?]
* Probleme: Wie in den Confluence Edit Mode commen, Stichwort "Markup"


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== PPS-1123 [Nicht technisch] Onboarding Dietmar
* https://hermesgermany.atlassian.net/browse/PPS-1123[Jira]
// link:../.ticket/1123.adoc[]
* [ ] Login Einführung AWS
* [ ] Login Einführung GCP
* [ ] Bestellstatus PC? Für Montag

* [ ] Jira Search anlegen

* [x] Linux ansprechen: Temuri Isabekovi, Markus Detlefsen
* [ ] Masterplan was ist das Kann-schulung
* [ ] React TanStack Table anschauen


* [ ] Was machen die 3 QR Codes exchange-pool, kundenlager, starkverkehrlager






== #####################################################################################################################






* Mindmap *Zukunft Strategie Plan Idee Ziel*, Beruflich, Privat, Wohnort, Einkommen
* Fenster waschen
* lernen Tour komplett



== Motto
* Wenn Du etwas loslassen möchtest, musst Du es erleben: Funk, Angeln, QRP. Plane das Erleben!
* Fokus gegen Unruhe, Bewußt-Sein! Verbinde das 3. Chakra, Achte was Du in deinen Kopf lässt.



== First Level Backlog
* link:../prv/backlog.adoc[Second-Level-Backlog]
* [ ] O-W 60 Backup-DVD Medien und Md5 Dateien strukturieren
  **         Backup großer Video Dateien überlegen, wie inkrementell sichern. Einen Notes/.archive und Notes/.backup Ordner anlegen,
             dort md5 der Dateien speichern. Archive = Cloud ohne git, doppelt gesichert.  Backup = M-Disc md5 Dateien. dot Ordner damit ausgeschlossen vom normalen grep.
             Für Archive könnte man ein Skript schreiben. Wichtig ist die M-Discs zu benennen. Nur in der Hülle!. Archiv md5 Dateien machen keinen Sinn. Vielleicht nur die Directory Struktur.
* [ ] FdW XX Versicherungen adoc anlegen, strukturieren. Solange 60 wiederholen bis fertig
* [ ] M-W 60 Start Einstellen Kleinanzeigen/eBay
* [ ] O-- 60 Task counter einbauen. Zählt runter 0. rauf. Hat aber im Scrum auch nicht interessiert. Frog Regel anhängen
* [ ] O-- 40 Alle adoc aus office einsortieren. Prüfen ob bei Fahrräder rechnung verlinkt und Rahmennummer angegeben.










''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Eichengrund Übertragungsvertrag

* *Raveling*: anrufen und Fragen klären
  ** [ ] WVL Raveling Fuger angebot?
  ** [ ] Marion Birgfeld anrufen
  ** Haus und Grund Mitgliedschaft?
  ** Nebenkostenabrechnung 2024 ist noch nicht da

link:../fnz/immo/eichengrund-haus.adoc[]



''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Gesundheit
* [ ] F-- 30 < ? > KKasse wechseln

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Haus
* [ ] H-- 30 < ? > Ladestecker bauen -> PausenJob


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''


== Notizen


|===
| Mail Privat |Cal Privat |Müll  |Sport  |Alarm |Buchen
| Mail Custom |Cal Custom |Brief |Chat   |Daily |
|===

