include::{root}/.inc/includeDaily.adoc[]

= Mittwoch, 27. März 2024

link:../fnz/office.adoc[Regeln]


== Aufgaben
State: ' ' Unplanned, B = Blocked, X = Done, R = Refine it!, W = Wiedervorlage, S = Selected
Themen: G Gesundheit, J Job, F Finanz, P Privat, H Haus, O Orga, M Minimalismus


== Motto
* Wenn Du etwas loslassen möchtest, musst Du es erleben: Funk, Angeln, QRP. Plane das Erleben!



== Bald
* [ ] O-W 60 Backup-DVD Medien und Md5 Dateien strukturieren
  **         Backup großer Video Dateien überlegen, wie inkrementell sichern. Einen Notes/.archive und Notes/.backup Ordner anlegen,
             dort md5 der Dateien speichern. Archive = Cloud ohne git, doppelt gesichert.  Backup = M-Disc md5 Dateien. dot Ordner damit ausgeschlossen vom normalen grep.
             Für Archive könnte man ein Skript schreiben. Wichtig ist die M-Discs zu benennen. Nur in der Hülle!. Archiv md5 Dateien machen keinen Sinn. Vielleicht nur die Directory Struktur.
* [ ] F-W 60 Google AusgabenProMonat ins vault holen
* [ ] FdW XX Versicherungen adoc anlegen, strukturieren. Solange 60 wiederholen bis fertig
* [ ] M-W 60 Start Einstellen Kleinanzeigen/eBay
* [ ] Fdw 20 Anruf: Neues DKB Konto aktivieren, es fehlt das start passwort. Oder brauche ich garnichts aktiverien?
* [ ] M-- 60 Kleidung aussortieren und sammeln.
* [ ] O-- 60 Task counter. Zählt runter o. rauf. Hat aber im Scrum auch nicht interessiert. Frog Regel anhängen
* Frag Dich, in welchen Job würdest du sogar in den Vertrieb gehen.
* Fragen gespräch sortieren wie bei chat gpt
* DeviN was ist das für eine KI
* Mercedes BWB eintragen https://mail.google.com/mail/u/0/?pli=1#inbox/FMfcgzGxSRMQpnJblCwFSjmkrSNFkjWP

== Frog FIRST!!!
* Bewerbung fertig machen
* Schimmel Mail

== Bewerben Routine
* https://mail.google.com/mail/u/0/?pli=1#inbox[Nur Bewerber Mails]
* https://www.xing.com/chats[]

== HEUTE ###############################################################################################################
* [ ] JDW 60 Intersoft 9:00Uhr Vorbereiten
* [x] BWB Übersichtsseite erstellen

* [ ] JdW 60 BEWERBEN! Jeden Tag Routine!
* [ ] JdW 60 Profil updaten mit QCC Task und Clock
* [ ] J-- 60 Lernen Angular: Clock weiter das umsetzen was bei UD gezeigt, oder ChatGPT, Hauptsache Ergebnis.

* [ ] F-w 20 info@tobias-diekmann.de aus Achim fragen!







''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Eichengrund Übertragungsvertrag
link:../fnz/immo/eichengrund-uebertragung.adoc[Stand]
* [ ] Perso mitnehmen! Kalendereintrag beachten

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== OLB OberesJüchen Anlage
* [W] Frau Reents von der OLB fragt nochmal nach, welche Möglichkeiten es gibt.

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Gesundheit
* [ ] G-W 30 < ? > 29.01 Urologe besuchen, Zettel + m. gefüllter Blase Mo-Fr 8:30 - 11:00 Mo-Do 15:00 - 18:00.
* [ ] F-- 30 < ? > KKasse wechseln

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Eichengrund Schimmel
* [S] Fdw 20 info@tobias-diekmann.de aus Achim fragen!

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Haus
* [ ] H-- 30 < ? > Ladestecker bauen -> PausenJob
* [ ] Hdw 60 < ? > Stromfresser finden, was ist mir son Server wert.

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Lernen
* [ ] Jdw 99 < ? > Projekt Wecker / Uhr Website starten
  ** Angular, spring boot
* [ ] Udemy Kurs DDD ist echt gut!

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''


== Notizen


|===
| Mail Privat |Cal Privat |Müll  |Sport  |Alarm |Buchen
| Mail Custom |Cal Custom |Brief |Chat   |Daily |
|===

