include::{root}/.inc/includeDaily.adoc[]

= Mittwoch, 31. Januar 2024

link:../def/score-board.adoc[Daily Score Board]

== Aufgaben
Themen: G Gesundheit, J Job, F Finanz, P Privat, H Haus, O Orga

* 4DX anwenden: 1 Ziele bestimmen 2 Messparameter 3 Board 4 Meetings
* Use backlog to keep overview in daily work
* link:../prv/backlog.adoc[BackLog]

== Zeiten
08 - 12 Lernen
12 - 14 Office: Olb, Cosmos, Eichengrund
14 - 18 Haus: Minimal, Regal, Aufräumen
18 - 21 Sport
21 - 22 Fernsehen



== Heute: Ziel immer W




* cloud / system leeren


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Neuer Job
* [ ] Fdw 10 Vertrag durchlesen
* [ ] Fdw 60 VM Linux anlegen.


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Eichengrund Übertragungsvertrag
link:../fnz/eichengrund-uebertragung.adoc[Stand]
* [W] Fdw 45 < ? > 29.01 StB Thorsten Hiltmann, Steuerbüro Hiltmann & Plenter (Tel: 04941 98900 MoDo 8-17 Fr 8-13) wenden
* Termin zur Beurkundung mit Frau Schlüchting unter 04941/92366-15 absprechen
* [ ] Fdw 10 < ? > Termin mit StB Thorsten Hiltmann,

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== OLB OberesJüchen Anlage
* [W] F   10 < ? > 15.01 Stadt Esens, Anfrage Kontowechsel als Pfandgläubiger, warte auf Antwort
* [W] F w 00 < ? > 15.01 WVL OLB gibt, wartet auf Stadt Esens

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Bewerbungen
* [W] FD  00 < ? > 17.01 Antworten Leonhard Krauss mit Referenzen. Leonhard die Daten von Jürgen geschickt
* [W] Jdw 02 < ? > Was machen die Bewerbungen? https://docs.google.com/spreadsheets/d/1iJZIE0leBKod_TWfXyiVQ0Gmvw_JyV04gIuhUIqP0uQ/edit#gid=833871327[Bewerbung]

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Direktversicherung Steuern, Cosmos
* [W] StB Bahlburg Mail, welche Daten vom Handelsregister. Antwort da?
* [ ] Einsortieren TK wo ich wann war

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Arbeitslosengeld
* [W] FdW 10 < ? > 31.01. Wurde Geld bezahlt?

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Gesundheit
* [ ] G W 30 < ? > 29.01 Urologe besuchen, Zettel + m. gefüllter Blase Mo-Fr 8:30 - 11:00 Mo-Do 15:00 - 18:00.
* [ ] F   30 < ? > KKasse wechseln
* Ziel ein X nach dem anderen

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Eichengrund Schimmel
* [W] Fdw 10 < ? > 05.02 HR, war der Test bei seiner Immobilie erfolgreich?


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Haus
* [ ] P w 99 < ? > Stuben Regal bauen.
* [ ] H   30 < ? > Ladestecker bauen -> PausenJob
* [ ] Hdw 60 < ? > Stromfresser finden, was ist mir son Server wert.

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Lernen
* [ ] Jdw 99 < ? > Projekt Wecker / Uhr Website starten
  ** Vue, Spring-boot
* [ ] Udemy Kurs DDD ist echt gut!

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''


* [ ] Jdw 60 12 Plan erstellen! link:plan.adoc[Plan]









Zentrale Software Resoucen verteilung. Agiles, Java Springboot. Angular

4 Personen, 1 java, 2 DPort in, Ende Pharse 1, suchen seniorigeren Entwickler
6 Monate eher langfristig. Nahezu 100% Remote. Projekte Standort HH. Realität nachezu 100% Homeoffice wenn dann in HH
Bremen unwichtig.

* mittwoch | donnerstag























''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
== Neue Firma
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== JIRA-12345 Titel
* https://jira/JIRA-12345[JIRA]
* link:../.ticket/12345.adoc[Ticket]



''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
== Notizen


|===
| Mail Privat |Cal Privat |Müll  |Sport  |Alarm |Buchen
| Mail Custom |Cal Custom |Brief |Chat   |Daily |
|===

