include::{root}/.inc/includeDaily.adoc[]

= Montag, 12. Februar 2024

link:../def/score-board.adoc[Daily Score Board]

== Aufgaben
Themen: G Gesundheit, J Job, F Finanz, P Privat, H Haus, O Orga

* Haltung: Kein Kaffee, Use Workspace switcher
* 4DX anwenden: 1 Ziele bestimmen 2 Messparameter 3 Board 4 Meetings
* Use backlog to keep overview in daily work
* link:../prv/backlog.adoc[BackLog]

== Zeiten
08 - 12 Lernen
12 - 14 Office: Olb, Cosmos, Eichengrund
14 - 18 Haus: Minimal, Regal, Aufräumen
18 - 21 Sport
21 - 22 Fernsehen



== Heute: (Ziel immer W)
* Nachfragen bei foquos
* keepassxc ausprobieren. was geht mit keepassxc.cli kann man taks-enc verwerfen?

* 05 Anrufen Raveling wie war der Test an seiner Immobilie



''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Eichengrund Übertragungsvertrag
link:../fnz/eichengrund-uebertragung.adoc[Stand]
* [ ] Findeklee zusammenfassung durchlesen
* [ ] Termin zur Beurkundung mit Frau Schlüchting unter 04941/92366-15 absprechen

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== OLB OberesJüchen Anlage
* [W] Frau Reents von der OLB soll ein schreiben für die Stadt Esens aufsetzen


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Bewerbungen
* [W] FD  00 < ? > 17.01 Antworten Leonhard Krauss mit Referenzen. Leonhard die Daten von Jürgen geschickt
* [W] Jdw 02 < ? > Was machen die Bewerbungen? https://docs.google.com/spreadsheets/d/1iJZIE0leBKod_TWfXyiVQ0Gmvw_JyV04gIuhUIqP0uQ/edit#gid=833871327[Bewerbung]

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Gesundheit
* [ ] G W 30 < ? > 29.01 Urologe besuchen, Zettel + m. gefüllter Blase Mo-Fr 8:30 - 11:00 Mo-Do 15:00 - 18:00.
* [ ] F   30 < ? > KKasse wechseln

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Eichengrund Schimmel
* [W] Fdw 10 < ? > 09.02 HR, war der Test bei seiner Immobilie erfolgreich?


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Haus
* [ ] H   30 < ? > Ladestecker bauen -> PausenJob
* [ ] Hdw 60 < ? > Stromfresser finden, was ist mir son Server wert.

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Lernen
* [ ] Jdw 99 < ? > Projekt Wecker / Uhr Website starten
  ** Angular, spring boot
* [ ] Udemy Kurs DDD ist echt gut!

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
== Notizen


|===
| Mail Privat |Cal Privat |Müll  |Sport  |Alarm |Buchen
| Mail Custom |Cal Custom |Brief |Chat   |Daily |
|===

