include::{root}/.inc/includeDaily.adoc[]

= 2024-01-17

== Aufgaben 
Themen: G Gesundheit, J Job, F Finanz, P Privat, H Haus

* 4DX anwenden: 1 Ziele bestimmen 2 Messparameter 3 Board 4 Meetings
* Use backlog to keep overview in daily work
* link:../prv/backlog.adoc[BackLog]




=== Heute

* [ ] FDW JETZT Steuerberater vorbereiten

* [W] F   10 01 Stadt Esens, Anfrage Kontowechsel als Pfandgläubiger
  ** [W] F w 00 01 WVL OLB gibt, wartet auf Stadt Esens
* [W] FD  00 01 Antworten Leonhard Krauss mit Referenzen. Leonhard die Daten von Jürgen geschickt 17.01

* [ ] FdW 30 12 Steuern
* [ ] G W 10 01 Orthopäde Termin besorgen
* [ ] P w 99 01 Stuben Regal bauen.
* [ ] Fdw 10 12 Eichengrund Schimmel Bestandsaufnahme Schimmel Dokument fertig. Wie weiter? Raveling?

* [ ] Jdw 02 12 Was machen die Bewerbungen? https://docs.google.com/spreadsheets/d/1iJZIE0leBKod_TWfXyiVQ0Gmvw_JyV04gIuhUIqP0uQ/edit#gid=833871327[Bewerbung]
* [ ] FDW 60 12 Cosmos direkt abarbeiten, bei Fr. Bahlburg melden, warum hat sich cosmos nicht gemeldet?
* [ ] F   30 12 KKasse wechseln
* [ ] H   30 12 Ladestecker bauen -> PausenJob



* [ ] Jdw 60 12 Plan erstellen!




* [ ] Jdw 99 12 Projekt Wecker / Uhr Website starten
  ** Vue, Spring-boot

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Task States definieren
* Waren die anderen klassifizierungen hilfreich?
* O=Ongoing(Mein Ball, bin dran) W=Wiedervorlage(ich warte) B=Backlog(gibt wichtigeres)


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== CMD Tool Task
* [ ] weiter task printservice einbauen, Testen! Für Encryption


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Eichengrund

Zentrale Software Resoucen verteilung. Agiles, Java Springboot. Angular

4 Personen, 1 java, 2 DPort in, Ende Pharse 1, suchen seniorigeren Entwickler
6 Monate eher langfristig. Nahezu 100% Remote. Projekte Standort HH. Realität nachezu 100% Homeoffice wenn dann in HH
Bremen unwichtig.

* mittwoch | donnerstag

* Olb7459!






















''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
== Neue Firma
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== JIRA-12345 Titel
* https://jira/JIRA-12345[JIRA]
* link:../.cus/.kn/.ticket/12345.adoc[Ticket]



''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
== Notizen


|===
| Mail Privat |Cal Privat |Müll  |Sport  |Alarm |Buchen
| Mail Custom |Cal Custom |Brief |Chat   |Daily |
|===

