include::{root}/.inc/includeDaily.adoc[]

= 2024-01-07

== Aufgaben 
Themen: G Gesundheit, J Job, F Finanz, P Privat, H Haus

* 4DX anwenden: 1 Ziele bestimmen 2 Messparameter 3 Board 4 Meetings
* Use backlog to keep overview in daily work
* link:../prv/backlog.adoc[BackLog]

* [ ] FDW 30 12 Steuern
* [ ] Fdw 30 12 Eichengrund Schimmel Bestandsaufnahme Schimme Dokument fertig.

=== Kleinkram
* Hotel berlin rechnung ändern
* Antworten mit Referenzen
* Referenz fertig machen

* [ ] JDW XX 12 Was machen die Bewerbungen? https://docs.google.com/spreadsheets/d/1iJZIE0leBKod_TWfXyiVQ0Gmvw_JyV04gIuhUIqP0uQ/edit#gid=833871327[Bewerbung]
* [ ] FDW 60 12 DKB Überweiseung
* [ ] FDW 60 12 Cosmos direkt abarbeiten
* [ ] JDW 30 12 Profil updaten, recruiter informieren Anüler, FreiB & Fest
* [ ] FDW 60 12 Anrufen neuer StB, Thema Eichengrund übertragung

* [ ] JDW 30 12 Freelancer map, Börsen updaten!
* [ ] F   30 12 KKasse wechseln
* [ ] P   60 12 Bücher aussortieren und zurück schicken
* [ ] H   30 12 Ladestecker bauen -> PausenJob


=== Heute
* [ ] Jdw 60 12 Plan erstellen!



* [ ] Pdw 30 12 Zeichnungen: Stube Regal, Gewürzregal, Vogeltränke -> ebayKlAn raus suchen

* [ ] Jdw 99 12 Projekt Wecker / Uhr Website starten
  ** Vue, Spring-boot

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Task States definieren
* Waren die anderen klassifizierungen hilfreich?
* O=Ongoing(Mein Ball, bin dran) W=Wiedervorlage(ich warte) B=Backlog(gibt wichtigeres)


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== CMD Tool Task
* [ ] weiter task printservice einbauen, Testen! Für Encryption


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Eichengrund






























''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
== Neue Firma
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== JIRA-12345 Titel
* https://jira/JIRA-12345[JIRA]
* link:../.cus/.kn/.ticket/12345.adoc[Ticket]



''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
== Notizen


|===
| Mail Privat |Cal Privat |Müll  |Sport  |Alarm |Buchen
| Mail Custom |Cal Custom |Brief |Chat   |Daily |
|===

