include::{root}/.inc/includeDaily.adoc[]

= Mittwoch, 24. Juli 2024

link:../fnz/office.adoc[Regeln]

== Aufgaben
State: ' ' Unplanned, B = Blocked, X = Done, R = Refine it!, W = Wiedervorlage, S = Selected
Themen: G Gesundheit, J Job, F Finanz, P Privat, H Haus, O Orga, M Minimalismus
Task: SUp: Standup, Cur: Current




== HEUTE ###############################################################################################################
* Noch keinen Zugriff Confluence: https://hermesgermany.atlassian.net/wiki/spaces/MPT/pages/16908614/Produkt+MultiApp#Produkt:MultiApp-Intent:InventurDaten%C3%BCbermitteln(migrationnotwendig2.0.0%E2%86%922.5.0)

----
mkdir h2
Linux? sudo chown -R $(docker-compose exec keycloak id -u) keycloak-data/


Create User, Credentials...
clients->pps-assement-management->credentials->Button Regenerate->Copy Fied Client Secret nach .env.local nach  CLIENT_SECRET

Wie exportieren

psql --host=localhost --port=5432 --username=asset-management --dbname=asset-management --file=./asset-management.sql
----


----
* "null"-Werte filtern
* join statt extra select
* filter values alphabetisch sortieren
* "selected value" aus filter nehmen
* tests schreiben :D
----

=== Infrasturktur
* [ ] VPN und OneDrive installieren, zum Sync der pps.kdb
* [ ] Intellij Lizens auf Hermes umstellen




* Zugang zu google cloud
* Passwärter üpbertragen


== Daily ###############################################################################################################
=== Was habe ich gemacht
* [ ] Weiter Colum Filter implementierung eingebaut
* [ ] Version Rollback Task angelegt PPS-1164

=== Woran arbeite ich
* [ ] Filter für AM 1100 zusammen mit Amri

=== Was sollte ich tun:
* [ ] Support-Fähig ab September (von Jan)
* [ ] AWS GCP Account !!! & Einführung
* [ ] Release Prozess lernen, (Release Branch ist zweistellig!)

=== Was werde ich tun
* [ ] AM Aufsetzen Doku erstellen
* [ ] Arbeitsfähig MultiApp herstellen, kann sein das wir das schon haben
* [ ] Nachbereitung: Prüfen, ob alle änderung von sebastian im ma nötig
* [ ] Mit Amri die Filter funktion fertig bauen
* [ ] SDK Man installieren
* DIRD Doku in jira updaten

Projekte stacken in einer ide

=== Wo brauche ich Hilfe
* [ ] Rollback Ticket erstellen, falsches Board: https://hermesgermany.atlassian.net/browse/ACP-420[Falsches Board]
* [ ] Brauche Win10 Test für Docker extra_hosts (mac-api)
* [ ] Ob das in Ordnung ist: Ticket einlösen für codetalk
* [ ] Jonas Termin Learnings einstellen: Zebra nicht informiert, Andere Teams nicht in Test, Böse 2.18.2 -> die 2.17.0 als 2.18.3,Wie gehen wir prinzipiell mit Abhängigkeiten MAC UI, MA und API um?, Buildnummer immer update
* [ ] Ops Genie, zusammen mit EZSB?
* [ ] Wo finde ich, wie viele Urlaubstage ich habe? Wie feier ich Überstunden ab?
Interflex, VTag bei Interflex.




''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== PPS-1108 Kommentarfeld für User
* https://hermesgermany.atlassian.net/browse/PPS-1108[jira]
* link:../.ticket/1108.adoc[Notes]
* [ ] API: ScheduledTasksService Uhrzeiten auseinander ziehen, sinnvoller gestalten
* [ ] Soll in die 3.14 rein

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== PPS-1152 DIRD
* https://hermesgermany.atlassian.net/browse/PPS-1152[jira]
* link:../hms/hermes-dird.adoc[Notes]
* O--o Doku sammeln


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== PPS-1123 [Nicht technisch] Onboarding Dietmar
* https://hermesgermany.atlassian.net/browse/PPS-1123[Jira]
* [ ] Login Einführung AWS
* [ ] Login Einführung GCP
* [ ] Soti und SmartIT Einführung mit Mofid





==  ####################################################################################################################
==  #####################################################################################################################
==  #####################################################################################################################

* Rav anrufen
* Urlaub planen
* Fliegengitter bestelle, 7 Pläne machen mit zeichnung und masse und Bestellung der Teile
* CSS  Ausweis klar mit ChatGpt
* [ ] Brandkasse fragen, warum nur 25.000

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Eichengrund
* link:../fnz/immo/eichengrund-haus.adoc[]

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Gesundheit
* [ ] F-- 30 < ? > KKasse wechseln

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Haus
* [ ] H-- 30 < ? > Ladestecker bauen -> PausenJob
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

== Notizen

|===
| Mail Privat |Cal Privat |Müll  |Sport  |Alarm |Buchen
| Mail Custom |Cal Custom |Brief |Chat   |Daily |
|===