include::{root}/.inc/includeDaily.adoc[]

= Freitag, 15. März 2024

link:../fnz/office.adoc[Regeln]


== Aufgaben
Themen: G Gesundheit, J Job, F Finanz, P Privat, H Haus, O Orga

* Use backlog to keep overview in daily work
* link:../prv/backlog.adoc[BackLog]

* Merker Bezahlt: D: 400,65€ Hotel Berlin, 365 Frohberg Tantra Seminar, Fehlt: Marokko

== Motto
* Wenn Du etwas loslassen möchtest, musst Du es erleben: Funk, Angeln, QRP. Plane das Erleben!



== Bald
* [ ] OdW Paper Score board? Experiment.
* [ ] O-W Backup-DVD Medien und Md5 Dateien strukturieren, NC->project->backup-md5files
* [ ] O-W Backup großer Video Dateien überlegen, wie inkrementell sichern



== Heute! (Hier wird gearbeitet)
* [ ] 15:00 Hecke zuende schneiden
* [x] Heute Bahlburg antworten

(Steuer) Identifikationnummer von Wiltraud 11 Ziffern: 50 149 786 826




''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Start Minimalismus
* Keller.








''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== BITEP 20. - 24.03.
* [X] Event gebucht
* [X] Event bezahlt und Ticket-Druck im Ordner
* [X] Event Rechnung angepasst und gedruckt im Ordner
* [X] Bahn Hin- und Rückfahrt gekauft & gedruckt
* [x] Unterkunft gebucht
* [X] Unterkunft bezahlt und
* [ ] Unterkunft Rechnung gedruckt im Ordner. 400,65€
* [ ] Unterkunft Rechnung angepasst und gedruckt im Ordner
* [ ] Event und Unterkunft Details in Kalendar eingetragen
* [ ] StB: Event, Unterkunft, PKW-Km als PostIt da. Sonst nichts!

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Tantra Do 28.03 - Di 02.04, 6 Tage
* [X] Event gebucht
* [X] Event bezahlt und Ticket-Druck im Ordner
* [X] Event Rechnung angepasst und gedruckt im Ordner
* [ ] PKW planen!
* [X] Unterkunft gebucht
* [x] Unterkunft bezahlt und gedruckt im Ordner
* [X] Unterkunft Rechnung angepasst und gedruckt im Ordner -> BITEP VII Rechnung
* [ ] Event und Unterkunft Details in Kalendar eingetragen
* [ ] StB: Event, Unterkunft, PKW-Km als PostIt da. Sonst nichts!


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== BKK im Kloster
* [x] Event gebucht
* [x] Event bezahlt und Ticket-Druck im Ordner
* [ ] Event Rechnung? Man könnte ein zusätzliches Bitep erfinden
* [-] Bahn Hin- und Rückfahrt gekauft & gedruckt
* [x] Unterkunft gebucht
* [ ] Unterkunft bezahlt und gedruckt im Ordner
* [ ] Unterkunft Rechnung angepasst und gedruckt im Ordner
* [ ] Event und Unterkunft Details in Kalendar eingetragen
* [ ] StB: Event, Unterkunft, PKW-Km als PostIt da. Sonst nichts!






''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Eichengrund Übertragungsvertrag
link:../fnz/immo/eichengrund-uebertragung.adoc[Stand]
* [ ] Perso mitnehmen

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== OLB OberesJüchen Anlage
* [W] Frau Reents von der OLB fragt nochmal nach, welche Möglichkeiten es gibt.

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Gesundheit
* [ ] G-W 30 < ? > 29.01 Urologe besuchen, Zettel + m. gefüllter Blase Mo-Fr 8:30 - 11:00 Mo-Do 15:00 - 18:00.
* [ ] F-- 30 < ? > KKasse wechseln

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Eichengrund Schimmel
* [ ] Fdw 20 info@tobias-diekmann.de aus Achim fragen!


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Haus
* [ ] H-- 30 < ? > Ladestecker bauen -> PausenJob
* [ ] Hdw 60 < ? > Stromfresser finden, was ist mir son Server wert.

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Lernen
* [ ] Jdw 99 < ? > Projekt Wecker / Uhr Website starten
  ** Angular, spring boot
* [ ] Udemy Kurs DDD ist echt gut!

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''


== Notizen


|===
| Mail Privat |Cal Privat |Müll  |Sport  |Alarm |Buchen
| Mail Custom |Cal Custom |Brief |Chat   |Daily |
|===

