include::{root}/.inc/includeDaily.adoc[]

= Freitag, 19. Juli 2024

link:../fnz/office.adoc[Regeln]

== Aufgaben
State: ' ' Unplanned, B = Blocked, X = Done, R = Refine it!, W = Wiedervorlage, S = Selected
Themen: G Gesundheit, J Job, F Finanz, P Privat, H Haus, O Orga, M Minimalismus
Task: SUp: Standup, Cur: Current




== HEUTE ###############################################################################################################

=== Infrasturktur
* [ ] VPN und OneDrive installieren, zum Sync der pps.kdb
* [ ] Intellij Lizens auf Hermes umstellen




* Zugang zu google cloud





* Bedingungen für "Arbeitsfähig" definieren. ZB. ma>./gradlew clean build fehlerfrein

== Daily ###############################################################################################################
=== Was habe ich gemacht
* Kommentar funktion geliefert
* Weiterers Test bauen in der Filter funktion
* Dev-Team: Version zurück gedreht
  ** Problem Zebra hat das emdk verschoben
  ** mein gradle daemon lief auf 21
  ** mein jdk 11 war nicht vollständig installiert
.Stand Multiapp bei mir und Amri
----
Execution failed for task ':app:packageRelease'.
> A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
   > com.android.ide.common.signing.KeytoolException: Failed to read key hemes_multiapp_store_key from store "/home/dietmar/project/multiapp/app/de.hermes.multiapp.release.keystore": keystore password was incorrect
----
* Umsetzen Learnings: GradleDemon startet nie wieder mit jdk 21, JDK 11 vollständig installiert

=== Woran arbeite ich
* [ ] AWS GCP Account & Einführung
* [ ] Ideen für den DIRT Day, was sagt Jonas zu dem Stand
* [ ] Bookmarks sortieren
* [ ]


=== Was werde ich tun
* [i] Früher feierabend
* [i] Support-Fähig ab September (von Jan)
* [ ] Arbeitsfähig MultiApp herstellen, kann sein das wir das schon haben
* [ ] Nachbereitung: Prüfen, ob alle änderung von sebastian im ma nötig
* [ ] Mit Amri die Filter funktion fertig bauen
* [ ] Anmelden bei new@hermes
* [ ] SDK Man installieren

=== Wo brauche ich Hilfe
* [ ] Brauche Win10 Test für Docker extra_hosts (mac-api)
* [ ] Ob das in Ordnung ist: Ticket einlösen für codetalk
* [ ] Jonas Termin Learnings einstellen: Zebra nicht informiert, Andere Teams nicht in Test, Böse 2.18.2 -> die 2.17.0 als 2.18.3,Wie gehen wir prinzipiell mit Abhängigkeiten MAC UI, MA und API um?, Buildnummer immer update
* [ ] Ops Genie, zusammen mit EZSB?
* [ ] Wo finde ich, wie viele Urlaubstage ich habe? Wie feier ich Überstunden ab?
Interflex, VTag bei Interflex.


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== PPS-1108 Kommentarfeld für User
* https://hermesgermany.atlassian.net/browse/PPS-1108[jira]
* link:../.ticket/1108.adoc[Notes]
* [ ] API: ScheduledTasksService Uhrzeiten auseinander ziehen, sinnvoller gestalten
* [ ] Soll in die 3.14 rein

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== PPS-1152 DIRD
* https://hermesgermany.atlassian.net/browse/PPS-1152[jira]
* link:../hms/hermes-dird.adoc[Notes]
* O--o Doku sammeln


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== PPS-1123 [Nicht technisch] Onboarding Dietmar
* https://hermesgermany.atlassian.net/browse/PPS-1123[Jira]
* [ ] Login Einführung AWS
* [ ] Login Einführung GCP
* [ ] Soti und SmartIT Einführung mit Mofid





==  ####################################################################################################################
==  #####################################################################################################################
==  #####################################################################################################################

* Rav anrufen
* Urlaub planen
* Fliegengitter bestelle, 7 Pläne machen mit zeichnung und masse und Bestellung der Teile
* CSS  Ausweis klar mit ChatGpt
* [ ] Brandkasse fragen, warum nur 25.000

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Eichengrund
* link:../fnz/immo/eichengrund-haus.adoc[]

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Gesundheit
* [ ] F-- 30 < ? > KKasse wechseln

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Haus
* [ ] H-- 30 < ? > Ladestecker bauen -> PausenJob
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

== Notizen

|===
| Mail Privat |Cal Privat |Müll  |Sport  |Alarm |Buchen
| Mail Custom |Cal Custom |Brief |Chat   |Daily |
|===