include::{root}/.inc/includeDaily.adoc[]

= Freitag, 03. Mai 2024

link:../fnz/office.adoc[Regeln]
link:../def/score-board.adoc[Daily Score Board]

== Aufgaben
State: ' ' Unplanned, B = Blocked, X = Done, R = Refine it!, W = Wiedervorlage, S = Selected
Themen: G Gesundheit, J Job, F Finanz, P Privat, H Haus, O Orga, M Minimalismus


== Motto
* Wenn Du etwas loslassen möchtest, musst Du es erleben: Funk, Angeln, QRP. Plane das Erleben!
* Fokus gegen Unruhe, Bewußt-Sein!



== Bald
* [ ] O-W 60 Backup-DVD Medien und Md5 Dateien strukturieren
  **         Backup großer Video Dateien überlegen, wie inkrementell sichern. Einen Notes/.archive und Notes/.backup Ordner anlegen,
             dort md5 der Dateien speichern. Archive = Cloud ohne git, doppelt gesichert.  Backup = M-Disc md5 Dateien. dot Ordner damit ausgeschlossen vom normalen grep.
             Für Archive könnte man ein Skript schreiben. Wichtig ist die M-Discs zu benennen. Nur in der Hülle!. Archiv md5 Dateien machen keinen Sinn. Vielleicht nur die Directory Struktur.
* [ ] F-W 60 Google AusgabenProMonat ins vault holen
* [ ] FdW XX Versicherungen adoc anlegen, strukturieren. Solange 60 wiederholen bis fertig
* [ ] M-W 60 Start Einstellen Kleinanzeigen/eBay
* [ ] O-- 60 Task counter einbauen. Zählt runter 0. rauf. Hat aber im Scrum auch nicht interessiert. Frog Regel anhängen
* [ ] O-- 40 Alle adoc aus office einsortieren. Prüfen ob bei Fahrräder rechnung verlinkt und Rahmennummer angegeben.
* [ ] Lynx Depot eröffnen
* [ ] Marion Birgfeld anrufen
* [ ] Einkaufen
* [ ] Bewerbung Atlas Elektronik

* Sparplan IE00B6R52259 wieder aktivieren




Depot	1009782768
Cashkonto	0017614124
Bezeichnung	ISHARES MSCI ACWI ETF
ISIN	IE00B6R52259
WKN, Symbol	A1JMDF, IUSQ
Auftragsart	Sparplan
Betrag	200,00 EUR
Zahlungsweise	1. Tag im Monat, monatlich
Laufzeit	ab 01.12.2021



== Frog FIRST!!!


== Bewerben Routine
* https://mail.google.com/mail/u/0/?pli=1#inbox[Nur Bewerber Mails]
* https://www.xing.com/chats[]

== HEUTE ###############################################################################################################

* [ ] JdW 60 BEWERBEN! Jeden Tag Routine!
* Schreibtisch aufräumen
* [ ] WVL Raveling Fuger angebot?
* [ ] WVL Garage Leck Esens, Ingo ansprechen
* Tabnine prüfen als KI
* Lernziel: Aufbau infrastruktur HomeServer: docker kuba, logstash elastic nextcloud, angular-mit-login, github-actions
* Mindmap *Zukunft Strategie Plan Idee Ziel*, Beruflich, Privat, Wohnort, Einkommen
* Notar bezahlen
* Armband reparieren, Uhrmacher


=== Lernen  ############################################################################################################
* [ ] Angular link:../tec/web/angular-lernen.adoc[Ziele]



''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Eichengrund Übertragungsvertrag
link:../fnz/immo/eichengrund-uebertragung.adoc[Stand]
* [ ] Perso mitnehmen! Kalendereintrag beachten

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== OLB OberesJüchen Anlage
* [W] Frau Reents von der OLB fragt nochmal nach, welche Möglichkeiten es gibt.

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Gesundheit
* [ ] G-W 30 < ? > 29.01 Urologe besuchen, Zettel + m. gefüllter Blase Mo-Fr 8:30 - 11:00 Mo-Do 15:00 - 18:00.
* [ ] F-- 30 < ? > KKasse wechseln

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Eichengrund Schimmel
* [S] Fdw 20 info@tobias-diekmann.de aus Achim fragen!

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Haus
* [ ] H-- 30 < ? > Ladestecker bauen -> PausenJob
* [ ] Hdw 60 < ? > Stromfresser finden, was ist mir son Server wert.

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Lernen
* [ ] Jdw 99 < ? > Projekt Wecker / Uhr Website starten
  ** Angular, spring boot
* [ ] Udemy Kurs DDD ist echt gut!

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''


== Notizen


|===
| Mail Privat |Cal Privat |Müll  |Sport  |Alarm |Buchen
| Mail Custom |Cal Custom |Brief |Chat   |Daily |
|===

