include::{root}/.inc/includeDaily.adoc[]

= 2024-01-11

== Aufgaben 
Themen: G Gesundheit, J Job, F Finanz, P Privat, H Haus

* 4DX anwenden: 1 Ziele bestimmen 2 Messparameter 3 Board 4 Meetings
* Use backlog to keep overview in daily work
* link:../prv/backlog.adoc[BackLog]




=== Heute


* [ ] PDW 40 01 Packen
* [W] FDW 10 01 Arbeitsamt
* [ ] FdW 30 12 Steuern
* [ ] G W 10 01 Orthopäde Termin besorgen
* [ ] P w 99 01 Stubenregal bauen.
* [ ] JdW 60 01 t encrpytion auf simple umbauen uns OpenSSL irgendwie sichern
* [ ] Fdw 10 12 Eichengrund Schimmel Bestandsaufnahme Schimmel Dokument fertig. Wie weiter? Raveling?
* [W] F w 00 01 WVL OLB gibt Rückruf, Schickt online
* [ ] PdW 30 01 Aufteilen nach Dringend, Wichtig und WVL
* [ ] H   30 01 Vogeltränke mit schwimmenden dosen deckel mit kork. sonst Grillanzünder kaufen
* [ ] FD  00 01 Antworten Leonhard Krauss mit Referenzen. Jürgen Brardt Xing messages
* [ ] Jdw 02 12 Was machen die Bewerbungen? https://docs.google.com/spreadsheets/d/1iJZIE0leBKod_TWfXyiVQ0Gmvw_JyV04gIuhUIqP0uQ/edit#gid=833871327[Bewerbung]
* [ ] FDW 60 12 Cosmos direkt abarbeiten, bei Fr. Bahlburg melden, warum hat sich cosmos nicht gemeldet?
* [ ] F   30 12 KKasse wechseln
* [ ] H   30 12 Ladestecker bauen -> PausenJob



* [ ] Jdw 60 12 Plan erstellen! link:plan.adoc[Plan]




* [ ] Jdw 99 12 Projekt Wecker / Uhr Website starten
  ** Vue, Spring-boot

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Task States definieren
* Waren die anderen klassifizierungen hilfreich?
* O=Ongoing(Mein Ball, bin dran) W=Wiedervorlage(ich warte) B=Backlog(gibt wichtigeres)


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== CMD Tool Task
* [ ] weiter task printservice einbauen, Testen! Für Encryption


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Eichengrund






























''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
== Neue Firma
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== JIRA-12345 Titel
* https://jira/JIRA-12345[JIRA]
* link:../.ticket/12345.adoc[Ticket]



''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
== Notizen


|===
| Mail Privat |Cal Privat |Müll  |Sport  |Alarm |Buchen
| Mail Custom |Cal Custom |Brief |Chat   |Daily |
|===

