include::{root}/.inc/include.adoc[]

= Endpunkte

== Schema
=== GET /schema/definitions/attributes/{commKey}
[source, kotlin]
----
// Ein Merkmal
data class AttributeDefinition(
  ** override var id: String?,
  ** val opalAttributeIds: List<String>,
  ** val commKey: String,
  ** val type: DataType,
  ** val acceptableUnits: List<String>,
  ** val attributeProperties: AttributeProperties
  ** // ...
)
----

=== GET /schema/definitions/contexts/{id}
[source, kotlin]
----
data class AttributeContext(
  ** override var id: String?,
  ** val attributeId: String,
  ** val attributeValue: String,
  ** val relatedContextId: String? = null,
  ** val associatedAttributes: List<AttributeContextAssociation>? = null)
data class AttributeContextAssociation(
  ** val attributeId: String,                                         // Standard ID
  ** val attributeProperties: AssociationAttributeProperties? = null) // context-specific configuration
data class AssociationAttributeProperties( 
  ** val values: List<String>? = null,
  ** val multiValue: Boolean? = null,
  ** val fixed: Boolean? = null,
  ** val displayUnit: String? = null,
  ** val required: List<ReasonCode>?,
  ** val partnerDisplayProperties: AssociationPartnerDisplayProperties? = null,
  ** val customerDisplayProperties: AssociationCustomerDisplayProperties? = null,
)
----
=== GET /schema/definitions/contexts/ ? attributeCommKey attributeValueStartsWithFilter embed
[source, kotlin]
----
// 1. Call
id = Query( AttributeDefinition.commKey == attributeCommKey).id
// 2. Call
return  List<AttributeContext> Query( AttributeContext.attributeId == id 
  ** OR AttributeContext.attributeValue starts with attributeValueStartsWithFilter )
----
  **
=== PUT /schema/definitions/contexts/{contextId} {Body:AttributeContextCreateOrUpdateRequest}
  ** contextId -> AttributeContext.id

  ** POST /schema/definitions/contexts/ {Body:AttributeContextCreateOrUpdateRequest}
[source, kotlin]
----
  ** data class AttributeContextCreateOrUpdateRequest( // RequestBody
  ** val attributeCommKey: String? = null, // ...
  ** val attributeValue: String? = null,   // ...
  ** val relatedContextId: String? = null, // ...
  ** val associatedAttributes: List<AttributeContextAssociationCreateOrUpdateRequest>? = null)
----

=== DELETE /schema/definitions/contexts/{contextId}
  ** contextId -> AttributeContext.id



=== /schema/context-trees/attributes/{commKey} ? attributeValue
  ** commKey -> ContextTreeNode.attributeCommKey
Besonderheit: Beinhaltet eine Liste der Kinder, also aufgelöste Backreferenzen 

[source, kotlin]
----
data class ContextTreeNode(
  ** override var id              : String?,
  ** val contextDefinitionId      : String,
  ** val attributeCommKey         : String,
  ** val attributeValue           : String,
  ** val hasAssociatedAttributes  : Boolean,
  ** val childContexts            : List<ContextTreeNode>?)
----



=== /schema/structures/attributes/{commKey} ? attributeValue, paging...
commKey 1 -> 1 AttributeDefinition.commKey
AttributeDefinition.id 

[source, kotlin]
----
data class AttributeDefinition(
  ** override var id: String?,
  ** val opalAttributeIds: List<String>,
  ** val commKey: String,
  ** val type: DataType,
  ** val acceptableUnits: List<String>,
  ** val attributeProperties: AttributeProperties)

data class AttributeProperties(
  ** val values: List<String>,
  ** val multiValue: Boolean,
  ** val fixed: Boolean,
  ** val displayUnit: String,
  ** val required: List<ReasonCode>? = null,
  ** val partnerDisplayProperties: PartnerDisplayProperties,
  ** val customerDisplayProperties: CustomerDisplayProperties)
----

== Taxonomy-Tree

== Structure


