include::{root}/.inc/include.adoc[]

= Review

* Telefon aus
* Vorher proben


== Story 161

* Ich möchte kurz die Story 161 vorstellen, bei der es um die Live Anbindung der
  ** Strecke zu SIRIUS geht.

* Ich zeige die Story stellvertretend für meinen Kollegen Christian und

* Stellvertretend für SIRIUS, die die Schnittstellen zum Partner bereitstellen
  ** wird Felix netterweise im Anschluss das Ergebnis bei SIRIUS zeigen.

<Bildschirm teilen>

* Und teile hier gleich mal den Link. Diejenigen, die die Rechte beantragt haben, können sich
  ** die PBKs auch Live anschauen und bearbeiten.

* Initial wurden 7 PBK ausgewählt die man jetzt hier in der UI sehen kann.

  ** Der hier angezeigte Stand entspricht eins zu eins dem Stand von Opal Live.

* <Öffnen Inhalationsaufsätze>

  ** Der Stand, der hier angezeigt wird ist so jetzt auch Live verfügbar.

  ** Das Ergebnis, das nachher zum Partner ausgespielt wird, zeigt Felix gleich
  ** Anhand der PBK Inhalationsaufsätze die hier einen Produkt Typen mit 17 Merkmalen hat.

  ** Dann würde ich jetzt das Mikro an Felix weitergeben, der dann das Ergebnis im Postman zeigen wird.
  ** Danach bieten wir noch die Gelegenheit für Fragen

<Felix zeigt Postman>

* Das war es zu unserem Live-Gang, gibt es noch Fragen?



== Story 197, Import PBKs

=== Übersicht
* Ich möchte die Story anhand von 4 kleinen Use-Cases vorstellen, bei denen
  ** Die Produkt Basis Klasse (PBK) Hosen mit dem Merkmal (F) wie Farbe importiert wird.
* Die PBK muss immer neu sein, das mitgebrachte Merkmal darf existieren.
* Das Merkmal (E) wie Energieversorgung und die PBK Fernseher existieren bereits.
* Das Merkmal (E) hat im Standard zwei Ausprägungen: Batteriebetrieb und Netzbetrieb.
* Ein Merkmal im Standard ist hier voll-grün dargestellt und ermöglicht die Wiederverwendung durch andere PBKs.
* Die PBK Fernseher hat eine kontextspezifische Konfiguration bei der nur Netzbetrieb zugelassen ist.
* Eine kontextspezifische Konfiguration wird hier durch einen grünen Kreis symbolisiert, sie darf die Auswahl
  ** im Standard nur einschränken.
* Jede kontextspezifische Konfiguration hat noch eine hier unsichtbare Verbindung zur Standard Konfiguration

=== Use-Case 1. Zeile: Neues Merkmal
* Nach dem Import bleibt die PBK Fernseher mit ihrer kontextspezifischen Konfiguration unberührt erhalten.
* Da das Merkmal Farbe neu ist, wird es im Standard importiert.
* Die PBK Hosen wird importiert und referenziert das Merkmal Farbe direkt.

=== Use-Case 2. Zeile: Merkmal vorhanden
* Nach dem Import bleibt die PBK Fernseher immer noch unberührt
* Das Merkmal Farbe wird nicht importiert, da es in der Ausprägung schon vorhanden ist.
* Die PBK Hosen wird importiert und referenziert das schon vorhandene Farben Merkmal im Standard

=== Use-Case 3. Zeile: Merkmal vorhanden, aber andere Ausprägung unverwendet
* Neue Ausgangslage
* Der Fernseher benutzt auch Farbe und dieses Mal lässt er nur Gelb als Ausprägung zu.
* Das Merkmal Farbe wird importiert und erweitert die schon vorhandenen Farben.
* Die PBK Hosen wird importiert
* Da wir nicht möchten das es Hosen in (grün) gibt muss für diese PBK, ähnlich der des Fernsehern, eine kontextspezifische
  ** Konfiguration angelegt werden.

=== Use-Case 4. Zeile: Merkmal vorhanden, und im Standard verwendet.
* Neue Ausgangslage
* Der vorhandene Standard wird benutzt
* Damit jetzt nicht PBKs, die Farbe im Standard benutzt haben plötzlich (rot) als Auswahl erben, müssen alle
  ** verwendeten PBKs angepasst werden
* Immer wenn durch den Import der Standard erweitert wird, müssen alle den Standard nutzenden PBKs in kontextspezifische
  ** Konfigurationen gewandelt werden.
