include::{root}/.inc/include.adoc[]

= esp-scaling-support

[source,java]
.filename.java
----
@BucketMessageConsumer(bucketStoreNames = KNIE_MESSAGE_IMPORT, bucketKeyJsonPointer = "/bookingnumber")
public void importKnieMessage(UpdateContainerStatusMessage containerStatusMessage) {...}
----

* Gruppiert Eingangsdaten des gleichen Types nach "bucketKeyJsonPointer", steckt diese in Buckets, die von single Consumer abgearbeitet
  werden können.
* "id" ist meist etwas kundenspezifisches, wie bookingnumber. Sinn ist es, dass Nachrichten eines Kunden in derselben Reihenfolge abgearbeitet werden, wie sie eintrafen, aber trotzdem Multithreading genutzt werden kann.

== Code
[source,java]
.kn.knlogin.esp.scaling.bucketstore.AbstractBucketStoreTest.java
----
// Sammelt alle Nachrichten und gruppiert gleiche ids in gleiche Buckets
Bucketstore.addItem(String id, T item);

// Gibt einen Bucket zurück, bei dem die IDs gleich sind, zB. alle dieselbe "bookingNumber". Welche Id das ist, ist
// für den Thread unwichtig. Es gibt so viele Buckets, wie es unterschiedliche id (Gruppen) gibt.
Bucket<T> b = Bucketstore.getAvailableBucket();

// Gibt das erste Item einer möglichen Reihe von gleichen "bookingNumber" zurück
T item = Bucket.poll();
----


== Wie finden sich Rabbit Nachricht und Consumer
[source,java]
----
// Nur zur Kenntnis
class SeaShipmentKnieMessage implements KnieMessage                 // <1>
// ------------------------------------------------------------------------
// Sender: Shipment KnieImportService
amqpTemplate.convertAndSend(MY_Q_NAME, knieMessage, ...);           // <2>
// ------------------------------------------------------------------------
// Queue Erzeugung: Shipment QueueConfiguration
@Bean
@BucketStoreMessageDispatcher                                       // <3>
public Queue internalShipmentQueue() {
    return getSingleActiveConsumerQueue(MY_Q_NAME); }               // <4>
// ------------------------------------------------------------------------
//Message Empfänger; Shipment SeaShipmentKnieMessageConsumer
@BucketMessageConsumer(bucketStoreNames = KNIE_MESSAGE_IMPORT)      // <5>
public void updateShipment(SeaShipmentKnieMessage knieMessage) {}   // <6>
----
<1> Jede KnieMessage-Type kann ihren eigenen Consumer haben
<2> Es wird and die MY_Q_NAME eine KnieMessage geschickt. HIer eine SeaShipmentKnieMessage
<3> Die Annotation erzeugt einen Listener auf die Q. Wenn an dem bucket message dispatcher kein bucket store name gesetzt ist, dann löst er dispatcher es selber auf anhand des message payloads.
<4> getSingleActiveConsumerQueue erzeugt eine Rabbit Q.
<5> Methode wird registriert für diesen Namen und diesen Typen
<6> Methoden arg type filtert für diese Typklasse

