include::{root}/.inc/include.adoc[]

= FB Feature Branch Umgebungen.

link:deploy.adoc[deployen]
link:release-bauen.adoc[releasen]

* Hilfe von Janar Rahumeel


== feature branch in OpenShift anlegen

* Das Anlegen hier eintragen: https://wiki.int.kn/display/KNESP/Feature+branch+environment+overview[hier]

Anleitung im esp-review-app Projekt unter README.md!
[source, bash]
----
# See README.md aus review-app

# Coplete comandline offered from  https://console.emea.ocp.int.kn/add/all-namespaces "Dietmar Zabel" -> "Copy login command"
./oc login --token=sha256~dxclfvzcq7FO6jF4mAIkzBUQwiL8h9ZwcjEN2uz7oS4 --server=https://api.emea.ocp.int.kn:6443
./oc project cp-474844

# from https://wiki.int.kn/display/KNESP/Feature+branch+environment+overview
./review-app list
./review-app create knomp29003 W systemtest
----

* Danach den SBA Link und den Vanish Link raus suchen unter
  ** Web: Openshift: Networking -> Routes -> Search: spring-boot-admin-knompXXXXX...
  ** Eintragen in Unter https://wiki.int.kn/display/KNESP/Feature+branch+environment+overview[Environment]
  ** UND im Ticket für das Anlegen des FB Environments.

== Welche Version ist auf welchem Featurebranch installiert
* Openshift Console aufrufen,
* Links Networking -> Routes -> Search: spring-boot-admin-knompXXXXX
* In Spring boot admin (SBA) suchen nach zB. tms-export, dort die Zeile klicken.

== Finden der Docker Image Tag Namen
Eine Featurebranch Umgebung wird 1:1 von System Test kopiert, um die Features zu übernehmen, müssen die zugehörigen
Snapshot Versionen übernommen werden. Welche Vertikale das sind, sieht man in der Epic Story unter Branches.

* Im Browser URL: git <vertikale>
* bitbucket <build> button
* Select knomp21294 branch
* Click on the KNOMP nummer build, dann kommst du nach gitlab
  ** dort unten in der stage liste unter deploy den stage "push_image:branch" auswählen
  ** dort ganz nach unten scrollen, dort steht irgendwo:
`INFO[0029] Pushing image to docker-registry-default.apps.cluster1.emea.cp.int.kn/cp-385892/esp-eventlog:knomp-21294-introduce-unlink-shipment-function-in-esp`
* Interessant ist nur das was nach dem doppelpunkt kommt: knomp-21294-introduce-unlink-shipment-function-in-esp Das ist der {image-tag} im review-app modify Befehl.
* Falls das nicht klappt, im "Harbor" nach der vertikalen suchen dort der "name"

== To find the environment-id Letter see:
  ** https://wiki.int.kn/display/KNESP/Feature+branch+environment+overview


[source,bash]
.Deploy des 21294 Features in den Featurebranch
----
docker login harbor.emea.ocp.int.kn
./review-app login external.dietmar.zabel
# Spezial Passwort unter Lastpass -> featurebranch mit !!


./review-app modify {envname}  {vertical}              {image-tag}                                                   {environment-id}

./review-app modify knomp21294 esp-api-gateway          feature-knomp-21294-introduce-unlink-shipment-function-in-esp U
./review-app modify knomp21294 esp-eventlog             knomp-21294-introduce-unlink-shipment-function-in-esp         U
./review-app modify knomp21294 esp-oedi-data-bridge     feature-knomp-21294-introduce-unlink-shipment-function-in-esp U
./review-app modify knomp21294 esp-exceptions           feature-knomp-21294-introduce-unlink-shipment-function-in-esp U
./review-app modify knomp21294 esp-frontend             knomp-21294-introduce-unlink-shipment-function-in-esp         U
./review-app modify knomp21294 esp-ordershipping        knomp-21294-introduce-unlink-shipment-function-in-esp         U
./review-app modify knomp21294 esp-purchaseorder        feature-knomp-21294-introduce-unlink-shipment-function-in-esp U
./review-app modify knomp21294 esp-reporting            feature-knomp-21294-introduce-unlink-shipment                 U
./review-app modify knomp21294 esp-shipment             feature-knomp-21294-introduce-unlink-shipment                 U
./review-app modify knomp21294 esp-tms-export           feature-knomp-21294-introduce-unlink-shipment-function-in-esp U

# APIs
# esp-rest-api           [X] Prüfen, ob die released worden sind.
# esp-shared-massage-api [ ] Prüfen, ob die released worden sind.
# esp-tms-knie4          [X] Prüfen, ob die released worden sind ???
----

== Commit ID (SHA1) in Spring boot admin finden
Unter SBA->Wallboard (Waben-ansicht)->Vertikale Zelle anklicken->eine Zeile der gelisteten Pods anklicken ->
           (Linke Menu) Details -> ganz oben, gibt es eine Info Sektion mit git Unter-sektion dort: id:XXXX


.Current work
----
./oc login https://api.emea.ocp.int.kn:6443 --username=external.dietmar.zabel
./review-app modify knomp29003 esp-tms-export feature-knomp-29003 W
----

== Update / Change Vertical Version in Featurebrunch using OC Web Console
* Navigate to: Workloads->DeploymentConfigs, search for your vertical. Click!
* On Detailspage-> Tab YAML -> search for image: 'harbor.emea.ocp.int.kn/cp-385892/esp-tms-export:feature-knomp-33142'
* Change the feature-knomp-33142 to that image you need.
* Verify acceptance, same page -> Tab Pods, Pods should start with status "Creation"

== Database connection
* Projekt: esp-review-app

Man kann einen Tunnel anlegen, oder ins Terminal des Pods gehen, dort im Verzeichnis
`/opt/esp` gibt es Skripte zum löschen des DB Schemas. Das geschieht in Oracle durch
Löschen des Users. Ein `-` im Namen wird durch ein `_` ersetzt. Beim Create User ist
das Passwort immer `esp`

[source, bash]
.Mit Oracle verbinden
----
cd /c/data/esp-review-app
rebase

# Login to OpenShift 3: using https://console.cluster1.emea.cp.int.kn:8443/console/catalog
#                    4: Using https://console.emea.ocp.int.kn/add/all-namespaces
# Oben rechts im Profil Menu ->  "Copy Login Command"
# Type: ./oc <Paste> ergibt
./oc login https://api.emea.ocp.int.kn:6443 --token=ogw-MTrBEkTaBYNucLfaslP7HRgw24WYynyAnHYo3Eg
./oc login https://api.emea.ocp.int.kn:6443 --username=external.dietmar.zabel

# Select OpenShift project
./oc project  cp-474844

# Select feature branch, wenn unteres Skript benutzt wird.
vim feature-branch-injector.sh

# Portforwarding to oracle
./connect-to-oracle-on-feature-branch.sh

# Oder
./oc --namespace cp-474844 port-forward service/oracle-knomp21294 1521:1521

* In Intellij
  ** Name: FeatureBranch-Shipment
  ** jdbc:oracle:thin:@localhost:1521/XEPDB1
  ** user SHIPMENT Pwd esp
----
