include::{root}/.inc/include.adoc[]

= vorbereitung

== Teilnehmer 
* Tobias Rathjen aus Appen
* Sven Bartel 32, Reviewer, Architekt 
* HH Thalin porto
* Vorort so viel wie nötig, nach Bedarf

== Projekt Ordermanagement
* Nicht nur Fracht, sondern auch Order also Bestelldaten 
  ** Nicht nur Shipment tracking sondern auch Order tracking
* Multilevel kanban
* Monolitisches FE in Vue2 und TS
* openAPI mit Swagger
* YAML specs generieren die REST APIs server seitig und den TS Client
  ** Ergebnis sind generierte mvn module
* BE untereinander kommuniziert über Rabbit MQ
* Java 11, SpringBoot 2.7, Elastic search, OpenShift 3, Kibana  logstash, Oracle Jäger tracing, Performance Prometheus und Grafana,  
* 35 40 Services
* Bitbucket Gitlab
* Epic branch environments
  ** Feature Branch Environment in openShift

== Wissen
* **FCL** steht für Full Container Load, also volle Containerladung. Damit ist ein Container gemeint, der als Ganzes und verplombt auf Reise geht. Es spielt keine Rolle, ob der Behälter komplett gefüllt ist.
* **LCL** steht für Less Than Full Container Load, also eine Teilladung in einem Container. Es handelt sich um Stückgut oder Sammelgut, das in einem Behälter zusammen mit anderen Lieferungen zu transportieren ist. Konkret handelt es sich um eine geringere Menge, zu der zusätzlich eine andere Ware geladen werden kann
* ESP Enterprise Solution Plattform
