include::{root}/.inc/include.adoc[]

= Relinkage Unlinking

== Documentation

* https://jira.int.kn/browse/KNOMP-30061[Ticket]
* https://jira.int.kn/browse/KNOMP-21294[Epic]
* https://jira.int.kn/browse/KNESPR-797[Word document]
* unlink svg

== Reproduction

____
* Create a FCL Booking in general for sea freight LCL and FCL ?
* Bring it to at least "Transportation Execution - Started" aka link it to a Seafreight Shipment (8610 update)
* Unlink the Shipment and revert the booking via make change
* Switch from FCL to AIR and process the Booking again
* AIR shipment is created and connected to the booking (8610,0100, 0150 updates)
____

(TT=TimosTool, Op=KN-Operator, Sp=Supplier)

* (Sp) Booking anlegen...
* (Op) Plan transportation...
* (TT) HAWB leeren House Air Way Bill (Für Air freight)
* (  ) MAWB leeren Master Air Way Bill (Für Air freight)
* (  ) *SO Release* drücken -> 8610 1200 0160 B70 Dokument geht dann vom TimoTool(TMS) ans ESP, Dann
* (Op) Oben im Frontend die Tracking infos.
* (  ) *Make change* drücken, dann bin ich wieder ganz vor bei Booking Request.
* (  ) Trotzdem stehen oben noch die Tracken Daten im Frontend.
* (  ) Button *Unlink Button* drücken, und die Tracking daten oben sind nicht mehr da. (Op: ist fürs Freigaben des Laderaums verantwortlich!)
* (Sp) Jetzt kann man den Mode Of Transport wechseln -> *Air/HAWB*
* (  ) Alle Pflichtfelder ausfüllen.
* (  ) Bug1: Quotation Number ausfüllen, Bug2: Volume wird erst beim 2. mal berechnet
* (  ) Request Booking drücken -> Transportation Execution (Kein Transportation planning für Air Freight)
* (Op) Prüfen: Unter Monitoring -> Suche mit Booking Number, Linkes Type=EDIORD,
dann sieht man 2 Einträge, erst FCL dann AIR, das sagt das wir dem Mode of Transport gewechselt haben.
* (TT) *SO Release* drücken -> 8610 1200 0150 H01 Dokument geht dann vom TimoTool(TMS) ans ESP, Dann
* (Op) Refresh, Tracking Number fehlt, Flugdaten fehlen oben, falscher State: Shipping Order Release
* (Logstash:) Mit Booking number suchen

=== Unliking from OrderBooking
* ESP: AbstractEspShipment.orderBookingNumber = null (betrifft Esp-Air, -Sea & -MasterShipment)
* !ESP: Shipment.orderBookingNumber = null (betrifft Air- & SeaShipment

=== Relinkage (ShipmentLinkingService)
Air Shipments werden nicht ge-relinked! Sie laufen nicht durch diesen Code.
----
            db = findShipment(msg.shpNr)
relinkable: db.orderBookingNr == null          &&
            db.obTmsRef != msg.obTmsRef        &&
            findShipment(msg.obTmsRef) == null

            seaDb = findShipment(msg.shpNr)
relink:     seaClone = new SeaShpmnt(seaDb.shpNr).shipmentLevelStatus(Shipment_Canceled))
            seaDb.shpNr          = msg.obTmsRef.getValue()
            seaDb.orderBookingNr = msg.obTmsRef.getOrderBookingNumber()
            seaDb.obTmsRef       = msg.obTmsRef

            espDb = findShipment(msg.shpNr)
            espDb.shpNr          = msg.obTmsRef.getValue()
            espDb.orderBookingNr = msg.obTmsRef.getOrderBookingNumber()
            espDb.obTmsRef       = msg.obTmsRef
----
