include::{root}/.inc/include.adoc[]

= Hermes Mac Ui Docu

== Starten der localen dev environment
* `~/project/mac-api> docker-compose -f localSetup/docker-compose.yml up`
* i run DeviceManagementApplication, Profile: develop, local, local-overrides
* `~/project/mac-ui>  yarn run:debug-local`

== React
* Icons: https://react-icons.github.io/react-icons/
* Komponenten: shadcn

* CSS TailWind

== Cypress Tests laufen lassen
* Server starten mit `mac-ui> yarn run:cyp`
* Testsuite starten mit `mac-ui> yarn run:cypress`
  ** Without UI `yarn cypress run  --config-file ./test/integration/cypress.config.ts`
  ** With    UI `yarn cypress open --config-file ./test/integration/cypress.config.ts`

* Run it: In  Testsuite -> E2E click-> Chromium click->Start E2E in Chromium click-> Tab-Specs."Run 6 specs" click
* Trouble: Wenn festh채ngt bei loading... dann oben rechts "Run all Tests [R]" dr체cken. Vielleicht auch 2 mal
* Nur einen Test ausf체hren soll dann `it.("my-test"` 채ndern zu `it.only("my-test"`
* Mehr Debug Ausgaben mit: `export DEBUG=cypress:*`


