include::{root}/.inc/include.adoc[]

= Sieben Schritte

* Src: Aufwachen im 21. Jahrhundert

== Sieben Schritte zum Aufwachen

=== Schritt 1: Die Wünsche und Ziele erkenne
* Finde heraus, was Du wirklich willst
* "Wenn Du die Wahrheit finden willst, so sehr wie jemand der unter Wasser ist nach Luft und Sauerstoff verlangt,
  dann wirst Du inm selben Augenblicke aufwachen." Wenn man also so sehr nur noch das eine will, dann bewirkt das,
  dass alles andere Wollen aufhört
* Wie wichtig ist mir das Aufwachen? Bin ich bereit, alle anderen Ziele des Lebens dem unterzuordnen? Ist es mir
  wichtiger weiterzuleben oder aufzuwachen?
* Der Mensch verbraucht viel mehr Energie dafür, Schaden abzuwenden, und alles in dem Bereich zu lassen, wo es gerade ist,
  als Energie darauf zu verwenden, wirkliche Lebensziele zu erreichen. All das muss man erforschen. Es kommt oft vor, dass
  jemand sagt: "Ich will nicht mehr." Und dann stellt sich heraus, dass er mit Händen und Füßen bestrebt ist, zu halten,
  was er hat: Den Job nicht zu verlieren, den Grad an Gesundheit, den er hat, nicht einzubüßen, un nicht krank zu werden.
  Also bei dem "Was will ich?" muss ich auch immer fragen: "Was will ich nicht?"

[IMPORTANT]
====
Nur wenn mir das Aufwachen wichtiger geworden ist als alles andere, gibt es eine reale Chance, dass dieser Durchbruch
in den göttlichen Grund als das dauerhafte Sein in dieser tiefen Wirklichkeit auch geschieht.
====

=== Schritt 2: Die Bereitwilligkeit, alles zu fühlen und zu erfahren
* Er besteht darin, das ich mich ganz in das Gefühl hineinfallen lasse, mich ganz vom dem Gefühl erfassen lasse - und
  das wird dann richtig unangenehm, und zwar jedes Gefühl, nicht nur der Schmerz und die Angst, sondern auch die Freude
  wird unangenehm, wenn Du Dich vollkommen von ihr erfassen lässt, denn dann bekommst Du Angst, dass Du explodierst.
  Wohin mit dieser Angst? Viele sagen: "Oh, dann fange ich an zu tanzen." Aber das ist nur ein Ausagieren. Was passiert,
  wenn Du diesem Gefühl von Freude, dieser ganzen Energie von Wut, wenn Du die aushältst und innerlich in Dir geschehen
  lässt? DAnn zerreißt es Dich. Dann bist Du nicht mehr nur Beobachter.

* Johannes Tauler: Man muss die Gefühle ausleiden, vor allem die Angst, die auftaucht, wenn es denn recht zugeht. Das
  heißt, wenn auf dem spirituellen Weg keine Angst hochkommt, dan geht es nicht mit rechten Dingen zu.

* Wenn ich aufwachen will, habe ich keinen Grund, innerlich etwas zu verdrängen und abzuwehren. dann öffnet sich
  sozusagen der ganze Deckel. Es ist eine ganz andere Haltung: Bereit sein, alles zu fühlen, was da ist.

* Die Körperempfindungen sind unwichtig.

* Wichtig ist das, was Du fühlst, jetzt im Augenblick. Welche Stimmung ist gerade da? Ist da Ruhe oder Unruhe? Und ein
  Gefühl kann ganz zart sein, ganz wenig. Dann stelle Dir die Frage: "Wie reagiere ich auf das Gefühl?" Gehe ich dagegen
  an, oder gehe ich davon weg oder renne ich da hin? Oder darf es einfach da sein und ihc überlasse mich dem?

*  Alle Gedanken, alle Erklärungsversuche sind ein Weggehen. Werde Du zu dem Gefühl. Lass Dich so sehr in das Gefühl
   hineinfallen, dass Du zu dem Gefühl wirst. Dann kannst Du entdecken:
   Was macht das Gefühl mit mir? Dann die Augen wieder auf machen.

* Es komme zuerst die oberflächlichen Gefühle, dann kommen tiefere Gefühle, dann die existenziellen, Gefühle von Angst,
  Schmerz, Verzweiflung und schließlich kommt der Abgrund von allein.

* Selbst das Beobachten, das Wegschieben ist schon ein Tun, und dieses Tun ist bereits Identifizierung. Ich
  identifiziere mich nur dann nicht mit dem Gefühl, wenn ich nicht sage, dass es mein Gefühl ist und, dass ich etwas
  mit ihm tun muss, sondern wenn ich in mir die Gefühle hochkommen und auftauchen lasse, mich ganz davon erfassen lasse.
  Dann ist da nur ein Gefühl und niemand, der sich identifiziert. Das ist ein absolut wichtiger Aspekt dieser
  Angelegenheit. Da ist der zweite Schritt: Einen Weg zu finden zwischen der Meditation, der Gefahr der Dissoziation
  und der Therapie, bei der es darum geht, Gefühle auszudrücken und auszuagieren. Dazwischen einen Weg zu finden ist ein
  Meilenstein in der spirituellen Entwicklung.

=== Schritt 3: Die Position des Zuschauers

* Durch das künstliche, angestrengte und außenstehende Beobachten wird der Weg zum Aufwachen regelrecht verbaut. Die
  andere Verwirrung ist die: Ich will ganz fühlen, was da ist, und das reicht mir. Das Geheimnis besteht darin, dass Du
  zu hundert Prozent fühlst, Dich der Lebendigkeit hingibst und zu hundert Prozent Beobachter, Zeuge und Wahrnehmender
  bist. Normalerweise ist der Mensch weder wirklich lebendig - er beurteilt sich, bewertet sich oder ist nicht wirklich
  am Leben beteiligt -, noch ist er wirklich der Zuschauer des Lebens. Er ist weder das eine noch das andere. Als
  Beobachter ist er nur beurteilend, vergleichend, sich schlecht machend oder sich in den Himmel lobend. Die Lösung
  besteht darin, sich zu hundert Prozent dem Leben hinzugeben und gleichzeitig zu hundert Prozent nur der Wahrnehmende
  des ganzen Theaters zu sein, der ganzen Vorstellung, der ganzen Evolution des ganzen Kosmos.


=== Schritt 4: Die Muster Deines Lebens verstehen
* sich über die wesentlichen Muster des Lebens und meines Verhaltens bewusst werde. Dabei spielt das Enneagramm eine
  wichtige und hilfreiche Rolle.
* Du sollst nicht, wenn Du Deine Charakterfixierung gefunden hast, eine bessere Sechs werden,... Nichts davon. Du
  sollst anhalten. Und das geschieht durch zwei innere Schritte. *Erstens*, Du siehst mit der Charakterfixierung besonders
  deutlich, welchem Grundgefühl Du aus dem Weg gehst und welches Grundgefühl Dein Leben reguliert und bestimmt: die Angst.
  Es ist die Angst, nicht geliebt zu werden, die Angst die Kontrolle zu verlieren, und darauf aufbauend Gefühle von
  Wut, Neid, wieder Angst, Stolz oder Habgier. Indem Du das bemerkst, erkennst du, was die ganze Maschine antreibt.
  Die wichtigste Aufgabe besteht darin, dich diesem zugrundeliegenden Gefühl zuzuwenden, es zu erkunden, es zu erfahren
  und bereit zu sein, dem zu begegnen. Der *zweite* ist: Du siehst all diese Muster und zunächst bist Du ernüchtert,
  schockiert und beleidigt, weil es so demütigend ist, zu sehen, dass Du alles, von dem Du bisher dachtest, es sei
  deine originelle Schöpfung und deine „besondere“ Persönlichkeit, im Enneagramm beschrieben findest.
* Du entdeckst mit Hilfe des Enneagramms das Grundgefühl und die Grundleidenschaft
  deines Lebens und kannst dich dem stellen und dem begegnen.
* Du kannst gleichzeitig klar und deutlich dein spiritueller Freund sein. Du siehst die Muster, siehst, was da abläuft,
  und indem Du anhältst und bereit bist, das zu fühlen, kommen diese ganzen Muster zur Ruhe – und dann zeigt sich
  die Essenz, die darin enthalten ist.

link:fixierung.adoc[Einser Fixierung]

=== Schritt 5: Die Identifikation mit dem Körper beenden und den Körper durchlässig werden lassen

=== Schritt 6: Die Vergangenheit beenden

=== Schritt 7: Dem Tod und der Angst begegnen

