include::{root}/.inc/include.adoc[]

= Brigitte Koch Kersten Jahres Seminar 2023

* Mediator: juliajespers.beratung@gmail.com


== Übung 26.05.2023
Atme mit zwei drei Seufzern aus, (sagst nichts dazu), jeder 10min
1.	Was spürst, fühlst oder erfährst du gerade?
2.	Was geschieht, wenn du dich in dem, was du spürst, fühlst und erfährst jetzt liebevoll beachtest?

== Online Gefühle
* Wut: Was will ich denn anders haben, ich habe die Energie sch on. Wut kommt immer in der Folge von Trauer. Trauer in der Folge von Schmerz. IN der Wut muss man sich die Frage stellen, was will ich anders haben.
* Trotz ist das Gefühl das man auf sich besteht, auch wenn man noch nichts ändert.
* Was ist liebevolle Selbstbeachtung: Um so mehr Liebe erlebst Du in Dir. Ich erlaube mir mich für mich zu beachten. Dann steige ich aus der Trauma-welt aus.
* was ist das Liebevolle daran, das ich mich nicht für mich interessiere. Ich habe mich damit geschützt.
* Welche Liebe bin ich als mich verneinende?
* Im Trauma können wir nicht liebevoll mit uns sein.
* Lieb sein ist das Gegenteil von Liebe, denn du bist nicht du. Liebevoll sein ist das Gegenteil von lieb sein.
* Ich lasse meine Empfindungen Gefühle zu, damit bist du in einer anderen Welt. Manchmal sind die Gefühle so bedrohlich, dass wir Unterstützung brauchen.
* Ich gebe mir jetzt endlich die Zuwendung, die ich damals gebraucht hätte.
* Trennung = So zu lassen wie sie ist.
* Wofür ist es wichtig an dem Kampf festzuhalten. Du weißt nicht wie die Beziehung mit ihr gehen würde, wenn du nicht mit ihr kämpfst. Der Preis des nicht kämpfens ist das Gefühl als, wenn du sie verlieren würdest.
* Erlaube Dir die Dinge so zu machen, wie Du sie gerne hättest. (Hast Du das Problem?)

== 27.05.2023 (Selbstliebende BÜ)
* Für Sicherheit tun wir alles. Geben wir die auf entsteht Angst.
* Verschleiß durch Verspannungen die schon in der Kindheit angefangen haben.
* Sich zusammenreißen heisst Muskel Anspannungen.
* Todesangst fängt an mit leichten verunsicherungen an. Die Angst nicht zu wisseln wie das Leben geht jenseits der selbstverneinung.
* Wenn wir die Selbstliebe aktivieren können, ist das der Ausstieg
* Ich bin ja noch Liebe, dann ist an der Stelle das Trauma überwunden.

== Andrea Paul loslassen (55min)
* Was erschüttert Dich. Toxische Beziehung, wo was falsch gemacht.
* Collision 2 Personen im Trauma, nicht ungewöhnlich. Hoch dynamische und kompliziert, zu lange bei Mama, ist noch pubertierend. Frage ist müßig. Du hast es so gut gemacht wie du konntest. Es gbit bauch verbindungen. Du hast auch dein trauma an ihn weitergegeben, das ist normal. Das es dich schmerzt ist auch normal, man möchte nicht das kind verlieren, aber da kommen wir nicht drum herum, er will kj mit aller gewalt von dir weg. Er fühlt sich an dich gebunden, er weiß nicht wie das geht von Dir weg, das ärgert ihn, das frustriert ihn. Die Verbindung ist da, trotz der überlagerungen.
Als er klein war: Zeit war schon sehr schön...
Er ist sehr verbunden mit Dir. Es ist für einen Jungen ein großes Problem sich von seiner Mutter zu lösen.
Ich kann das wirklich verstehen, das das weh tut, es ist hilfreich für dich das du verinnerlichst das
Er will jemand eigenes werden, er weiß nicht, wie er dich loslassen kann. Vergegenwärtige, im Herzen seid ihr verbunden.
Ihm immer ein angebot machen.
Du kannst Zähne nicht aufhalten, dann hat er halt mit 30 nicht zähne. Er will das auf seine weise schaffen.
Vielleicht kennst du ja Jemand der ihn unterstützen kann? Nicht toxisch verwenden.
Er ist in der Pubertät, er will kein Paul-Andrea sein. Manche haben es da leichter da die werte kompatibel mit den der Eltern sind. Je tiefer und zarter sensibler die Liebe ist zwischen euch, desto schwieriger ist es euch zu trennen.
Aus der liebevollen umarmung sich zu trennen ist schwer, er muss Gewalt anwenden.
Vielleicht eine Sozialarbeiterische Betreuung.
Was ist denn das, was so weh tut? Narzisstische Kränkung, Anmaßung einen stabilen Menschen zu schaffen. Die Eltern machen nicht aus kindern irgendwas. Die haben ihr eigenes schicksal. Die Überlegungen sind nur Abwehr. Schuldfrage ist eine Abwehr.
Was ist das Schlimme? Ich möchte alles richtig machen. Ihc habs vermasselt tut weh.
Wie kann es sein, das Du jetzt gescheitert bist? Versuch mal zu spüren, wie alt du dich fühlst in dem Schmerz?
3 oder 4 Jahre, erlaube dir das. Was war denn da in dieser Zeit?
In einer verzauberten Welt. In der echten ist Angst und Nichts, da ist keiner da.
Aber sobald die 3-jährige sie verläßt, ist da nichts. Was ist da? Angst.
Dunkel bedrohlich. Es ist kalt, Es ist ruhig, Es ist starr. Unlebendig, Tod
Was fühlst du gerade? Bedrohung, vage Angst. Gehört mit dazu.
Kränkung ich will auch so frei sein wie mein Bruder. Du warst die Behinderte
Kränkung krank zu sein, die zu sein die nicht mitmachen kann.
Er hätte die wahl etwas aus meinen leben machen können, Ihc konnte nicht, und er will nicht.
Du musst das integrieren, damit du das nicht immer wieder in Paul siehst.
Er will sich freikämpfen von dieser Verstrickung. Wenn du da vorangehst, wird es für euch beide leichter.
Wenn ich die behinderte Andrea annehme ist das ein TEil des Erwachsen werden. Die kleine bunte zauberwelt ist noch da.
Beschrieben durch Astrid Lindgren und damit die schlimme Zeit überleben. Du wirst darin vieles von deiner kraft finden.
die kompetenzen beachten, die du erfahren hast um sowas zu überstehen, hast du noch nicht beachtet.
Die Kränkung darüber krank gewesen zu sein. Das Krank gewesen sein dir auch zu erlauben. Es war schlimmm, aber du hast was draus gemacht. Es gab auch schönes im Leben.
Ein gottes hadern, wie kann das sein, wie kannst du mir sowas antun.
Schockverabeitung Zittern
In allem was auftaucht sich liebend selbst beachten
Ach das ist ein Schock, man ist innerlich so leer, Zittern, weinen zulassen
'''
* Netz: Das wichtigste ist zu vergeben. Denn wenn du es nicht tust macht dich der Hass zu genau dem Menschen, der du nicht sein wolltest.

== Probleme
* Relativ schlecht im Fühlen glaube ich
* Verspannungen, Steife Körperhaltung, manchmal auch geistig steif was Planungen angeht.
* Langweile und Entspannung fehlen, stattdessen unruhe
* Statt Angst Wut, Angst nicht fühlen wollen
* Ab und Zu Jäh-zorn, ähnlich wie mein Vater
* Trauma aus der Vergangenheit: Geschlagen in der Kindhheit und Vernachlässigung.
* Gefühle nicht erlauben,
  ** weil wer so weich ist hätte mir auch nicht geholfen als ich so klein war.
  ** das ist gegen mein Wertesystem.




sich zu wehren ist
körperarbeit, Claudia.
Herzschlag ist schwäche, erlauben verletzlich zu sein.

== Trauma und Gefühle
* T = Erleben unerträglicher Gefühle situativ, unertrträgliches zu lösen durch Abspaltung.
* T = Folge der Fremdverneinung, du solltest liebe weg oder anders sein. Todes bzw. Vernichtungsangst = nicht bleibt nicht mal die seele
* Wenn das T Moment wiederholt fühlt das zur frendverneinung. Daraus ergibt sich eine Selbstverneinung. Die noch schwerer ist aufzulösen. = Selbtverneinung = Selbstschutz
* Schlimme Gefühle und damit alleine gelassen wurde. Wenn dann ein Erwachsener ohne Angst und ohne Gewinn .
* Selbstverneiunung = ich bin weertlos, = selbstverneinung. Den wir mit aller kraft uns selbst zu eigen gemacht haben.
* Partnerwahl, Eine stufe liebevoller als das im zuhause war.
* Wie wäre ich denn damals selber gerne behandelt worden. Damit befriedigen wir das Bedürfnis.
* Mensch der uns in dieser Situation aushält, das kann sehr heilsam sein. Es geht nur um einen ganz einfachen menschlichen Beistand. D.h. ich bleibe bei dir in deiner Not, ich halte es mit dir zusammen aus. Das ist dann heilend.
* 1. Schritt, Wahrzunehmen und zuzulassen was gerade ist, nicht manipulativ, = liebevoll sein
* 2. SChritt sich für mich zu interessieren. Ich möchte mir den Raum geben damit das was ist da sein darf.
* Ich habe das Körpergefühl und bleibe dabei und interessiere mich für das Gefühl. Die haltung was genau erlebe ich da eigentlich.  Das wäre es gewesen was uns füehlte zum Trauma start. Jemanden der sich dafür interessiert hätte. DAs Herz ausschütten. Das ist liebevolle Selbstbeachtung. Selber Liebe zu sein. Wir steigen aus der Erfahrung aus unfassbarer lieblosigkeit aus. T = Erfahung unfassbaer lieblosigkeit. DA wo mir lsB glingt beende ich das Trauma.
* 4 Stufen der Selbstbejahung
* Je mehr ich das übe desto mehr Sicherheit habe ich das ich die Liebe die ich mir gewünscht hätte letzendlihc selbst in mir trage.
* Definition: Liebe ist das aufbauende, demgebenüber: Herrschaft und Zerstörung
* Du kriegst von mir keine Träne zu sehen. Mit dem Gefühl absoluter Trotz. Stark. Trotz ist dort sehr gensund. DAs du deine Würde verteidigt hast.
* Depressiver fühlt nicht,

* Vernichtungssehnsucht
  ** Endlich ruhe
  ** Verrückte Konstrukt von dem Selbstkonzept als folge von T Erfahren, das alles los  zu werden und zu dem zu kommen,
wer du in Wahrheit bist. Ego gedöns loswerden.

* Spirituelles Trauma, verlassen von Gott .

== Übung 28.05
* 20min Zeit, wenn früher fertig bei 1 wieder anfangen, muss nicht alle Fragen beantwortet

1.	`Ich bin` (Wie fühlt es sich an, wenn ich mich vergegenwärtige, dass ich bin. Nur die zwei Worte wirken lassen, die Einzige Erfahrung, an der es keinen Zweifel gibt.)
2.	`Was geschieht, wenn ich mich in die Erfahrung meines Seins tiefer hineinfallen lasse?`
3.	`Was spüre, fühle und erfahre ich jetzt?`
Empfehlung BÜ 4 Stufen der Selbstbejahung jeden Tag zu machen. Grundüberzeugungen, GEdankenautobahnen, die dann Folgen haben, um denen entgegenzuwirken müssen wir unsere Aufmerksamkeit auf etwas anderes lenken. Im Trauma war das nicht möglich. Es bilden sich neue Neuronen im Hirn, es braucht Übung damit das alte überwachsen wird. Alte Erfahrungen können sich verändern, wir können raus kommen. Wir müssen aber die neuen Erfahrungen immer wieder machen. Angeblich 3600 mal. Es msuss schon viel passieren um sich von überlbensmustern zu trennen. Es ändert sich dann auch etwas.

== Martha Müller
Schmerz = 2 Dinge: Gewahr wie schlimm es war, angesichts dessen das jetzt gerade anders ist.
Schämen folgt immer auf das Erleben von Schuld. Es war unangemessen, das du dir den Raum genommen hast. Du nimmst Dich nicht so wichtig. So hat man dir dich zurück zu nehmen und du hast es geglaubt. Du hast dann weniger Angriffe bekommen.
Wenn wir schuld seien, seien wir schlecht. Wir erreichen nicht unschuldig zu sein. Einer sicht sich immer im Nachteil. Wenn wir immer unschuldig sein wollen, verzweifeln wir weil wir das nicht erreichen können. Die Grßen haben uns glauben lassen wür müssen unschuldig sein. DAs geht aber nicht. Uralte kulturell bedingte geschichte.
Du hast gewählt welche Schuld du sein möchtest. Jeztz gilt es die Verantwortung dafür zu übernehmen. WEche schuld will ich sen, ich trage dann die schuld die ich bin. Wenn ich die schuld doch nicht sein will, dann kann man sagen, das einem das Leid tut.
Man kann sich nicht ent-schuldigen, man kann die schuld nicht loswerden. Ne super strategie um machnen zu könenn was man will. Werückt sich entshculdigen.

== Gabriele
Tut gut wenn du dich verstanden fühltst. Endlich sicher zu sein.
Übdrall wo du im Mitgefühl bist
Du hast Dich für Dich eingesetzt
Reinzenierung, Narzistische Kränkung
Auszittern bei claudia
was ist verloren? Was ist die Lüge? Was kotzt dich so an?

== Peergruppen
1 bis 2 mal im Monat. Life oder Online, Chat
0177-4925280 Meike

* Trauma heilungs tagebuch anlegen.

== Übung
* MIt Wertschätzung und Interesse zuhören, dadurch entsteht der Raum.
1.	die Grundübung in liebevoller Selbstbeachtung:
  a.	Was spürst, fühlst oder erfährst du gerade?
  b.	Was geschieht, wenn du das, was du spürst und fühlst jetzt ganz zulässt?
  c.	Was geschieht, wenn du dich in dem, was du gerade spürst und fühlst liebevoll beachtest und dein Herz für dich öffnest?

zu zweit, Frage 1, Partner antwortet, Aufgabe des Ich verstehens, Ich Brigitte erlebe gerade dies und das, sagt gabe. Ich habe dann die Aufgabe das zu korrigieren. Du als suchende wirst dir nochmal klarer.
Was weißich denn intuitiv was ich noch gar nicht gewußt habe. Ich verstehen, Korrektur

Frage stellen ; Antwort entgegennehmen ; Ich-Verstehen: Ich… erlebe/ fühle/ ; Korrektur

2.	Dyade:
  a.	Was spürst, fühlst oder erfährst du gerade?
  b.	Welche intuitiv erfahrbare tiefer Wahrheit verbirgt sich in dem, was du gerade gesagt hast?
  c.	Was fühlst du dazu, wie du dich dir gerade zuwendest?

Klosterfreiheit 37,
Vegan melden