include::{root}/.inc/include.adoc[]

= übungen

== Tonübung
== Bewußtheitsübung
== Bewegungsübung
== Holotropes Atmen

== Schmelzatmen
Es wird durch Druck ein Schmerz erzeugt auf einer Verspannten Stelle umd das Gefühl in Erinnerung
zu rufen, das nicht gefühlt worden ist, das durch Muskelanspannung weggedrückt worden ist, um es
jetzt zu fühlen und zu lösen.

== Unbekannter Author
1. Wählen Sie eine selbstbeschränkende Überzeugung, die Sie davon abhält, das Glück und die Freude zu erleben, die Sie verdienen. Fragen Sie sich: „Was wäre, wenn diese Überzeugung überhaupt nicht der Realität entspricht? Was würde ich dann tun?“ Wie auch immer Ihre Antwort ausfällt: Handeln Sie so, als wäre ein Scheitern ausgeschlossen. Dann kann Sie nichts und niemand mehr aufhalten!
2. Stellen Sie sich vor, es gäbe in Ihrem Leben nichts, was Sie nicht sein, tun oder haben könnten. Geld, Ideen, Begabung, Fähigkeiten, Wissen, Erfahrung, Mitarbeiter oder Kontakte: Was wäre, wenn Sie alles hätten, um das zu erreichen, was Sie wirklich wollen? Was würden Sie als Erstes in Ihrem Leben und in Ihren Beziehungen ändern?
3. Wenn Ihr Leben absolut perfekt wäre, wie würde es dann aussehen? Worin würde es sich von dem Leben unterscheiden, das Sie heute führen?
4. Trainieren Sie das „Zurück aus der Zukunft“-Denken: Schauen Sie fünf Jahre in die Zukunft und blicken Sie dann zurück auf den heutigen Tag. Überlegen Sie: Wie kommen Sie von dem Punkt, an dem Sie gerade stehen, dorthin, wo Sie in Zukunft sein wollen? Was muss passieren? Welche Schritte müssen Sie dazu unternehmen?
