include::{root}/.inc/includeDaily.adoc[]

= Donnerstag, 20. Juni 2024

link:../fnz/office.adoc[Regeln]
link:../def/score-board.adoc[Daily Score Board]

== Done
* 07:00 - 09:00
* 09:00 - 11:00
* 11:00 - 13:00
* 13:00 - 15:00
* 15:00 - 17:00

== Aufgaben
State: ' ' Unplanned, B = Blocked, X = Done, R = Refine it!, W = Wiedervorlage, S = Selected
Themen: G Gesundheit, J Job, F Finanz, P Privat, H Haus, O Orga, M Minimalismus


//       ###############################################################################################################
== HEUTE ###############################################################################################################

* Linux ansprechen: Temuri Isabekovi, Markus Detlefsen
* Masterplan was ist das Kann-schulung
* React TanStack Table anschauen

* [ ] Buchen



* Mindmap *Zukunft Strategie Plan Idee Ziel*, Beruflich, Privat, Wohnort, Einkommen
* Fenster waschen
* lernen Tour komplett



== Motto
* Wenn Du etwas loslassen möchtest, musst Du es erleben: Funk, Angeln, QRP. Plane das Erleben!
* Fokus gegen Unruhe, Bewußt-Sein! Verbinde das 3. Chakra, Achte was Du in deinen Kopf lässt.



== First Level Backlog
* link:../prv/backlog.adoc[Second-Level-Backlog]
* [ ] O-W 60 Backup-DVD Medien und Md5 Dateien strukturieren
  **         Backup großer Video Dateien überlegen, wie inkrementell sichern. Einen Notes/.archive und Notes/.backup Ordner anlegen,
             dort md5 der Dateien speichern. Archive = Cloud ohne git, doppelt gesichert.  Backup = M-Disc md5 Dateien. dot Ordner damit ausgeschlossen vom normalen grep.
             Für Archive könnte man ein Skript schreiben. Wichtig ist die M-Discs zu benennen. Nur in der Hülle!. Archiv md5 Dateien machen keinen Sinn. Vielleicht nur die Directory Struktur.
* [ ] FdW XX Versicherungen adoc anlegen, strukturieren. Solange 60 wiederholen bis fertig
* [ ] M-W 60 Start Einstellen Kleinanzeigen/eBay
* [ ] O-- 60 Task counter einbauen. Zählt runter 0. rauf. Hat aber im Scrum auch nicht interessiert. Frog Regel anhängen
* [ ] O-- 40 Alle adoc aus office einsortieren. Prüfen ob bei Fahrräder rechnung verlinkt und Rahmennummer angegeben.

== Frog FIRST!!!









''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Eichengrund Übertragungsvertrag

* *Raveling*: anrufen und Fragen klären
  ** [ ] WVL Raveling Fuger angebot?
  ** [ ] Marion Birgfeld anrufen
  ** Haus und Grund Mitgliedschaft?
  ** Nebenkostenabrechnung 2024 ist noch nicht da

link:../fnz/immo/eichengrund-haus.adoc[]



''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Gesundheit
* [ ] F-- 30 < ? > KKasse wechseln

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Haus
* [ ] H-- 30 < ? > Ladestecker bauen -> PausenJob


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''


== Notizen


|===
| Mail Privat |Cal Privat |Müll  |Sport  |Alarm |Buchen
| Mail Custom |Cal Custom |Brief |Chat   |Daily |
|===

