include::{root}/.inc/includeDaily.adoc[]

= Donnerstag, 18. Juli 2024

link:../fnz/office.adoc[Regeln]

== Aufgaben
State: ' ' Unplanned, B = Blocked, X = Done, R = Refine it!, W = Wiedervorlage, S = Selected
Themen: G Gesundheit, J Job, F Finanz, P Privat, H Haus, O Orga, M Minimalismus
Task: SUp: Standup, Cur: Current




== HEUTE ###############################################################################################################

=== Infrasturktur
* [ ] AWS GCP Einführung
* [ ] VPN und OneDrive installieren, zum Sync der pps.kdb
* [ ] Intellij Lizens auf Hermes umstellen


Böse 2.18.2 !
die 2.17.0 als 2.18.3

* sdkman installieren
* Zugang zu google cloud
SDK man installieren?
GradleDaemon wrum immer falsches jdk
broadcastreceiver intend datawedge profile
Ticket einlösen für codetalk



* Zebra- Url ändern, wissen das alle?
* Abnahme geht nicht nur mit PPS.
* Bedingungen für "Arbeitsfähig" definieren. ZB. ma>./gradlew clean build fehlerfrein

== Daily ###############################################################################################################
=== Done
* Kommentar funktion geliefert
* Weiterers Test bauen in der Filter funktion
* Dev-Team: Version zurück gedreht
  ** Problem Zebra hat das emdk verschoben
  ** mein gradle daemon lief auf 21
  ** mein jdk 11 war nicht follständig installiert
.Stand multiapp
----
Execution failed for task ':app:packageRelease'.
> A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
   > com.android.ide.common.signing.KeytoolException: Failed to read key hemes_multiapp_store_key from store "/home/dietmar/project/multiapp/app/de.hermes.multiapp.release.keystore": keystore password was incorrect
----
* Umsetzen Learings: GradleDemon startet nie wieder mit jdk 21, JDK 11 vollständig installiert

=== Doing
* [ ] Prüfen ob alle änderung von sebastian im ma nötig
* [ ] Ops Genie, zusammen mit EZSB?
* [ ] Mit Amri die Filter funktion fertig bauebn
* [ ] Brauche Win10 Test für Docker extra_hosts (mac-api)
* [ ] Montag: Wie gehen wir prinzipiell mit Abhägigkeiten MAC UI, MA und API um?, Buildnummer immer update
* [ ] Urlaub planen, wie geht das? Wo dokumentiert? erst mit dem Team besprechen, syl+whei= 1 Tag
* [!] Früher feierabend





3.14 kommentarfunktion



* Soti und SmartIT Einführung mit Mofid


== Fragen --------------------------------------------------------------------------------------------------------------


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== PPS-1108 Kommentarfeld für User
* https://hermesgermany.atlassian.net/browse/PPS-1108[jira]
* link:../.ticket/1108.adoc[Notes]
* [ ] API: ScheduledTasksService Uhrzeiten auseinander ziehen, sinnvoller gestalten

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== PPS-1152 DIRT
* https://hermesgermany.atlassian.net/browse/PPS-1152[jira]
* link:../.ticket/1152.adoc[Notes]
* O--o Doku sammeln


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== PPS-1123 [Nicht technisch] Onboarding Dietmar
* https://hermesgermany.atlassian.net/browse/PPS-1123[Jira]
* [ ] Login Einführung AWS
* [ ] Login Einführung GCP


==  ####################################################################################################################
==  #####################################################################################################################
==  #####################################################################################################################

* Rav anrufen
* Fliegengitter bestelle, 7 Pläne machen mit zeichnung und masse und Bestellung der Teile
* CSS  Ausweis klar mit ChatGpt
* [ ] Brandkasse fragen, warum nur 25.000

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Eichengrund
* link:../fnz/immo/eichengrund-haus.adoc[]

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Gesundheit
* [ ] F-- 30 < ? > KKasse wechseln

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Haus
* [ ] H-- 30 < ? > Ladestecker bauen -> PausenJob
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

== Notizen

|===
| Mail Privat |Cal Privat |Müll  |Sport  |Alarm |Buchen
| Mail Custom |Cal Custom |Brief |Chat   |Daily |
|===