include::{root}/.inc/includeDaily.adoc[]

= Freitag, 08. März 2024

link:../def/score-board.adoc[Daily Score Board]

== Aufgaben
Themen: G Gesundheit, J Job, F Finanz, P Privat, H Haus, O Orga

* Use backlog to keep overview in daily work
* link:../prv/backlog.adoc[BackLog]

* Merker Bezahlt: D: 400,65€ Hotel Berlin, 365 Frohberg Tantra Seminar, Fehlt: Marokko

== Motto
* Wenn Du etwas loslassen möchtest, musst Du es erleben: Funk, Angeln, QRP. Plane das Erleben!



== Bald
* [ ] OdW Paper Score board? Experiment.
* [ ] O-w yubikee verwendet, wie unter Android?
* [ ] O-w vault in cloud, damit keepass zugriff erhält
* [ ] O-W Zeugnismappe einmal komplett einscannen
* [ ] O-W Backup-DVD Medien und Md5 Dateien strukturieren
* [ ] O-W Backup großer Video Dateien überlegen, wie inkrementell sichern
* [ ] O-W Accounts.odt entfernen, drucken. Office löschen und neue anlegen


== Heute! (Hier wird gearbeitet)
* [w] JDW Bewerbung raus. "Suche immer noch... ANÜ, FB, Fest"
* [ ] Vertrag drucken, Parameter ausarbeiten
* [ ] J-W merge vault & kh + Folgetätigkeiten
* [ ] J-W pwd aus environment entfernen. Githubkey entfernen. env_pwd manuell pflegen nur auf Stick

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== kh & vault merge
* server, p5470, e5401, A54, Cinnamon, labor
* Zuerst säubern.



== Zeitstrahl

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Esens 08 - 10.03 Vertragsparameter
* [ ] Mit Mutti Parameter des Vertrages klären


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Bhhz 15 - 17.03 Vorstieg


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== BITEP 20. - 24.03.
* [X] Event gebucht
* [X] Event bezahlt und Ticket-Druck im Ordner
* [X] Event Rechnung angepasst und gedruckt im Ordner
* [X] Bahn Hin- und Rückfahrt gekauft & gedruckt
* [x] Unterkunft gebucht
* [ ] Unterkunft bezahlt und gedruckt im Ordner. 400,65€ Rechnung fehlt noch
* [ ] Unterkunft Rechnung angepasst und gedruckt im Ordner
* [ ] Event und Unterkunft Details in Kalendar eingetragen
* [ ] StB: Event, Unterkunft, PKW-Km als PostIt da. Sonst nichts!

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Tantra Do 28.03 - Di 02.04, 6 Tage
* [X] Event gebucht
* [X] Event bezahlt und Ticket-Druck im Ordner
* [X] Event Rechnung angepasst und gedruckt im Ordner
* [ ] PKW planen!
* [X] Unterkunft gebucht
* [x] Unterkunft bezahlt und gedruckt im Ordner
* [X] Unterkunft Rechnung angepasst und gedruckt im Ordner -> BITEP VII Rechnung
* [ ] Event und Unterkunft Details in Kalendar eingetragen
* [ ] StB: Event, Unterkunft, PKW-Km als PostIt da. Sonst nichts!

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== BKK
* [x] Event gebucht
* [x] Event bezahlt und Ticket-Druck im Ordner
* [ ] Event Rechnung? Man könnte ein zusätzliches Bitep erfinden
* [-] Bahn Hin- und Rückfahrt gekauft & gedruckt
* [x] Unterkunft gebucht
* [ ] Unterkunft bezahlt und gedruckt im Ordner
* [ ] Unterkunft Rechnung angepasst und gedruckt im Ordner
* [ ] Event und Unterkunft Details in Kalendar eingetragen
* [ ] StB: Event, Unterkunft, PKW-Km als PostIt da. Sonst nichts!






''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Eichengrund Übertragungsvertrag
link:../fnz/eichengrund-uebertragung.adoc[Stand]
* [ ] Termin zur Beurkundung mit Frau Schlüchting unter 04941/92366-15 absprechen

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== OLB OberesJüchen Anlage
* [W] Frau Reents von der OLB fragt nochmal nach, welche Möglichkeiten es gibt.

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Gesundheit
* [ ] G-W 30 < ? > 29.01 Urologe besuchen, Zettel + m. gefüllter Blase Mo-Fr 8:30 - 11:00 Mo-Do 15:00 - 18:00.
* [ ] F-- 30 < ? > KKasse wechseln

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Eichengrund Schimmel
* [W] Fdw 10 < ? > 09.02 HR, war der Test bei seiner Immobilie erfolgreich?


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Haus
* [ ] H-- 30 < ? > Ladestecker bauen -> PausenJob
* [ ] Hdw 60 < ? > Stromfresser finden, was ist mir son Server wert.

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Lernen
* [ ] Jdw 99 < ? > Projekt Wecker / Uhr Website starten
** Angular, spring boot
* [ ] Udemy Kurs DDD ist echt gut!

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''


== Notizen


|===
| Mail Privat |Cal Privat |Müll  |Sport  |Alarm |Buchen
| Mail Custom |Cal Custom |Brief |Chat   |Daily |
|===

