include::{root}/.inc/includeDaily.adoc[]

= Montag, 18. März 2024

link:../fnz/office.adoc[Regeln]
link:../def/score-board.adoc[Daily Score Board]

== Aufgaben
State: ' ' Unplanned, B = Blocked, X = Done, R = Refine it!, W = Wiedervorlage, S = Selected
Themen: G Gesundheit, J Job, F Finanz, P Privat, H Haus, O Orga, M Minimalismus


* Use backlog to keep overview in daily work
* link:../prv/backlog.adoc[BackLog]

* Merker Marokko Restbetrag

== Motto
* Wenn Du etwas loslassen möchtest, musst Du es erleben: Funk, Angeln, QRP. Plane das Erleben!



== Bald
* [ ] OdW 60 Paper Score board Erstellung Experiment.
* [ ] O-W 60 Backup-DVD Medien und Md5 Dateien strukturieren
  **         Backup großer Video Dateien überlegen, wie inkrementell sichern. Einen Notes/.archive und Notes/.backup Ordner anlegen,
             dort md5 der Dateien speichern. Archive = Cloud ohne git, doppelt gesichert.  Backup = M-Disc md5 Dateien. dot Ordner damit ausgeschlossen vom normalen grep.
             Für Archive könnte man ein Skript schreiben. Wichtig ist die M-Discs zu benennen. Nur in der Hülle!. Archiv md5 Dateien machen keinen Sinn. Vielleicht nur die Directory Struktur.
* [ ] F-W 60 Google AusgabenProMonat ins vault holen
* [ ] FdW XX Versicherungen adoc anlegen, strukturieren. Solange 60 wiederholen bis fertig
* [ ] M-W 60 Start Einstellen Kleinanzeigen/eBay
* [ ] Fdw 20 Anruf: Neues DKB Konto aktivieren, es fehlt das start passwort. Oder brauche ich garnichts aktiverien?
* [ ] Pdw 60 Hosen kaufen
* [ ] M-- 60 Kleidung aussortieren und sammeln.

== Bewerben Routine
* https://mail.google.com/mail/u/0/?pli=1#inbox[Nur Bewerber Mails]
* https://www.xing.com/chats[]

== Heute! (Hier wird gearbeitet)
* [ ] JDW 60 BEWERBEN! Jeden Tag Routine!
* [ ] JDW 60 Profil updaten mit QCC

* [ ] Task Verify. Wegen häufiger Refactorings. Linking your Thinking?
* [ ] Fdw 20 info@tobias-diekmann.de aus Achim fragen!



''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Start Minimalismus
* Keller.



== Zeitstrahl


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== BITEP 20. - 24.03.
* [X] Event gebucht
* [X] Event bezahlt und Ticket-Druck im Ordner
* [X] Event Rechnung angepasst und gedruckt im Ordner
* [X] Bahn Hin- und Rückfahrt gekauft & gedruckt
* [x] Unterkunft gebucht
* [X] Unterkunft bezahlt und
* [ ] Unterkunft Rechnung gedruckt im Ordner. 400,65€
* [ ] Unterkunft Rechnung angepasst und gedruckt im Ordner
* [ ] Event und Unterkunft Details in Kalendar eingetragen
* [ ] StB: Event, Unterkunft, PKW-Km als PostIt da. Sonst nichts!

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Tantra Do 28.03 - Di 02.04, 6 Tage
* [X] Event gebucht
* [X] Event bezahlt und Ticket-Druck im Ordner
* [X] Event Rechnung angepasst und gedruckt im Ordner
* [ ] PKW planen!
* [X] Unterkunft gebucht
* [x] Unterkunft bezahlt und gedruckt im Ordner
* [X] Unterkunft Rechnung angepasst und gedruckt im Ordner -> BITEP VII Rechnung
* [ ] Event und Unterkunft Details in Kalendar eingetragen
* [ ] StB: Event, Unterkunft, PKW-Km als PostIt da. Sonst nichts!


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== BKK im Kloster
* [x] Event gebucht
* [x] Event bezahlt und Ticket-Druck im Ordner
* [ ] Event Rechnung? Man könnte ein zusätzliches Bitep erfinden
* [-] Bahn Hin- und Rückfahrt gekauft & gedruckt
* [x] Unterkunft gebucht
* [ ] Unterkunft bezahlt und gedruckt im Ordner
* [ ] Unterkunft Rechnung angepasst und gedruckt im Ordner
* [ ] Event und Unterkunft Details in Kalendar eingetragen
* [ ] StB: Event, Unterkunft, PKW-Km als PostIt da. Sonst nichts!






''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Eichengrund Übertragungsvertrag
link:../fnz/immo/eichengrund-uebertragung.adoc[Stand]
* [ ] Perso mitnehmen

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== OLB OberesJüchen Anlage
* [W] Frau Reents von der OLB fragt nochmal nach, welche Möglichkeiten es gibt.

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Gesundheit
* [ ] G-W 30 < ? > 29.01 Urologe besuchen, Zettel + m. gefüllter Blase Mo-Fr 8:30 - 11:00 Mo-Do 15:00 - 18:00.
* [ ] F-- 30 < ? > KKasse wechseln

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Eichengrund Schimmel
* [S] Fdw 20 info@tobias-diekmann.de aus Achim fragen!

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Haus
* [ ] H-- 30 < ? > Ladestecker bauen -> PausenJob
cdcdd* [ ] Hdw 60 < ? > Stromfresser finden, was ist mir son Server wert.

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Lernen
* [ ] Jdw 99 < ? > Projekt Wecker / Uhr Website starten
** Angular, spring boot
* [ ] Udemy Kurs DDD ist echt gut!

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''


== Notizen


|===
| Mail Privat |Cal Privat |Müll  |Sport  |Alarm |Buchen
| Mail Custom |Cal Custom |Brief |Chat   |Daily |
|===

