include::{root}/.inc/includeDaily.adoc[]

= Mittwoch, 07. August 2024

link:../fnz/office.adoc[Regeln]

== Aufgaben
State: ' ' Unplanned, B = Blocked, X = Done, R = Refine it!, W = Wiedervorlage, S = Selected
Themen: G Gesundheit, J Job, F Finanz, P Privat, H Haus, O Orga, M Minimalismus
Task: SUp: Standup, Cur: Current




== HEUTE ###############################################################################################################

link:../hms/hermes-uebung.adoc[Üben]



== Daily ###############################################################################################################

Steckerleisten checken!!!

https://hermesgermany.atlassian.net/browse/PPS-1191[LastTest ticket]

=== Was habe ich gemacht
PPS-1151 AM Keycloak einrichten und dokumentieren
PPS-1151 AM Backend Tests, sehen soweit gut aus, coverage...
PPS-1119 Lobster von 4h auf 25h


https://hermeseuropegmbh.sharepoint.com/:p:/r/sites/TeamPPS/Freigegebene%20Dokumente/General/Reviews/2024-08-08/Abteilungsroutine-2024-08-08.pptx?d=w2ea129471c8a43ada6f61ff2187e0658&csf=1&web=1&e=zkBfRU[Abteilungsroutine-2024-08-08.pptx]

* DIRD Fragen und Learning Tasks sortiert, weiter






=== Woran arbeite ich gerade
* [ ] DIRD: Übersicht über alles


=== Was sollte ich tun:
* git Graph bauen, States beim Releasen
* [ ] Infra VPN und OneDrive installieren, zum Sync der pps.kdb
* [ ] Infra Intellij Lizens auf Hermes umstellen
* [ ] Infra Passwörter aus browsers üpbertragen
* [ ] Mongo DB läuft nicht: https://learn.mongodb.com/
* Graph Offline OnLine Anmeldung
* [ ] Column Filter Tests schreiben


=== Was werde ich tun





=== Später
* [ ] SDK Man installieren
* [ ] Brauche Win10 Test für Docker extra_hosts (mac-api)


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== <Task-Driver>Lasttest kickoff MAC
* https://hermesgermany.atlassian.net/browse/PPS-1191[jira]

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== <!DRIVER!> PPS-1151 Test Filter function
* https://hermesgermany.atlassian.net/browse/PPS-1151[jira]
* link:../.ticket/1151.adoc[Details]



''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== WVL Was machen mit diesen Tasks?
* [ ] (01) Fehlendes URL Logging, welche URL braucht wie lange?
* [ ] (02) Fehlende Lasttests
* [ ] (03) Doku Normalfall-Release fehlt (Wen warnen,..., Terra-form neu deployen!,  Überlegung ob gleichzeitig zu releasen, zum Schluss mit Tag auf Live setzen.)
* [ ] (04) Bug: Warum hat der Renovate im mac-ui auf dem Release Branch committed?
* [ ] (05) Bug: Gradle retrieve version startet möglicherweise immer auf der falschen Version. (Ist das schon gefixt?)
* [ ] (06) Pipeline fixes aus mac-api release/3.13.0 cherry-picken
* [ ] (07) Task: Missing HW Upgrade nachpflegen
* [ ] (08) Version Rollback: Doku und Pipe fehlt -> PPS-1164
* [ ] (09) Key-rotation laut Aikido dokumentieren und planen
* [ ] (10) DB Backup einspielen: Doku fehlt
* [ ] (11) NEU: Git Release fixen: Release Branch X.Y   1.Tag & Commit Release: X.Y.0
* [ ] (12) NEU: MAC-API: Task erstellen: ScheduledTasksService Uhrzeiten auseinander ziehen, sinnvoller gestalten, in Ordnung?



=== PPS-1164 Rollbackversion erstellen
* https://hermesgermany.atlassian.net/browse/PPS-1164[jira]
* [ ] Montag im Planning ansprechen Zusammen mit


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== PPS-1184 User steckt in Overlay fest
* https://hermesgermany.atlassian.net/browse/PPS-1184[jira]
* link:../.ticket/1184.adoc[Details]


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== <!DRIVER!> PPS-1152 DIRD
* https://hermesgermany.atlassian.net/browse/PPS-1152[jira]
* link:../hms/hermes-dird.adoc[Notes]



''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== PPS-1123 [Nicht technisch] Onboarding Dietmar
* https://hermesgermany.atlassian.net/browse/PPS-1123[Jira]
* [ ] Login Einführung AWS
* [ ] Login Einführung GCP
* [ ] Soti und SmartIT Einführung mit Mofid





== #####################################################################################################################
== #####################################################################################################################
== #####################################################################################################################

* [X] PDW 15 08 AAmt bezahlen, Bohlmann bezahlen
* [ ] JDW 20 08 Alle Zettel einsortiert
* [ ] P W 60 08 Brandkasse fragen, warum nur 25.000
* [ ] F w 15 08 Haus und Grund Mitgliedschaft!
* [x] J   60 08 Blech schneiden mit Rundung
* [x] GDW 60 -- Sport ab 19:15 Uhr
* [ ] F W -- 08 Rente, Zurich Cosmos wieder aktivieren; HR fragen ob sie das übernehmen
* [ ] P   60 08 cloud/audiobook anlegen alle Hörbücher aus doc dahin ziehen, Nextcloud auf dza-pps
* [ ] P   60 08 Rasen mähen
* [ ] Pd  60 08 TimeBox Hausputz
* [x] P w -- 08 WVL Mit Andrea Urlaub planen
* [ ] P   60 08 Fliegengitter Obi Holz schneiden, 8 Pläne machen mit zeichnung und masse und Bestellung der Teile


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Eichengrund
* link:../fnz/immo/eichengrund-haus.adoc[]

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Gesundheit
* [ ] F-- 30 < ? > KKasse wechseln

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Haus
* [ ] H-- 30 < ? > Ladestecker bauen -> PausenJob
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

== Notizen

|===
| Mail Privat |Cal Privat |Müll  |Sport  |Alarm |Buchen
| Mail Custom |Cal Custom |Brief |Chat   |Daily |
|===