= 5-Hindrances (Hindernisse)

* https://www.youtube.com/watch?v=4-079YIasck&t=567s&ab_channel=TEDxTalks[TED Talk]

Verhindern klar zu sehen, oder eine Entscheidung zu treffen.


|===
|*Sensual Desire*  |Verlangen   | seeking for pleasure through the five senses of sight, sound, smell, taste and physical feeling.
|*Ill Will*        |Widerwillen | feelings of hostility, resentment, hatred and bitterness.
|*Sloth-and-torpo* |Trägheit    | half-hearted action with little or no effort or concentration.
|*Restlessness*    |Unruhe      | the inability to calm the mind and focus one's energy.
|*Sceptical Doubt* |Zweifel     | lack of conviction or trust in one's abilities.
|===

VERLANGEN auch: Sinnliches Begehren, Gier „Ich habe Hunger“; „Ich wäre jetzt gerne in der Stadt beim Shoppen“; „Ich brauche jetzt einen Kaffee/Zigarette“ etc.

WIDERWILLEN auch: Widerstand, Ablehnung, Unzufriedenheit, Gereiztheit, Verweigerung und Hass „Die Anleitende hat eine unmögliche Stimme“; „Was mache ich hier eigentlich, das ist doch alles Blödsinn“ etc.

TRÄGHEIT auch: Müdigkeit/Schläfrigkeit, Mattigkeit, Langeweile, Stumpfheit „Ich könnte auf der Stelle einschlafen“; „Man, ist das langweilig“ etc.

UNRUHE auch: Ungeduld, Ruhelosigkeit, Aufgewühltsein Übermäßiges Interesses an etwas oder jemand anderem: „Hoffentlich veranstalten die Kinder zu Hause kein Chaos“, „Meine Kollegen müssen die ganze Arbeit in dieser Woche ohne mich schaffen“ etc.

ZWEIFEL auch: Skepsis Zweifel zeigt sich in der Meditation an inneren Sätzen wie: „Ich weiß gar nicht, ob ich das richtig mache“; „Ob das wirklich etwas für mich ist?“; „Wie soll mir das bei meinen Problemen im Alltag den helfen?“ etc.

