include::{root}/.inc/include.adoc[]

= Backlog Aufgabenstapel

== First Level Backlog
* link:../prv/backlog.adoc[Second-Level-Backlog]
* [ ] O-W 60 Backup-DVD Medien und Md5 Dateien strukturieren
  **         Backup großer Video Dateien überlegen, wie inkrementell sichern. Einen Notes/.archive und Notes/.backup Ordner anlegen,
dort md5 der Dateien speichern. Archive = Cloud ohne git, doppelt gesichert.  Backup = M-Disc md5 Dateien. dot Ordner damit ausgeschlossen vom normalen grep.
Für Archive könnte man ein Skript schreiben. Wichtig ist die M-Discs zu benennen. Nur in der Hülle!. Archiv md5 Dateien machen keinen Sinn. Vielleicht nur die Directory Struktur.
* [ ] FdW XX Versicherungen adoc anlegen, strukturieren. Solange 60 wiederholen bis fertig
* [ ] M-W 60 Start Einstellen Kleinanzeigen/eBay
* [ ] O-- 60 Task counter einbauen. Zählt runter 0. rauf. Hat aber im Scrum auch nicht interessiert. Frog Regel anhängen
* [ ] O-- 40 Alle adoc aus office einsortieren. Prüfen ob bei Fahrräder rechnung verlinkt und Rahmennummer angegeben.



== Lernen Job
* Udemy Lehrgang: https://www.udemy.com/course/microservices-clean-architecture-ddd-saga-outbox-kafka-kubernetes/learn/lecture/31152934?start=195#overview


== Aufgaben generell



''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
== Eichengrund
* [ ] F w XX 07 Garage leckt link:../fnz/immo/eichengrund-uebertragung.adoc[Stand]
* [ ] F w XX 12 Datenlogger besorgen

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
=== Weitere, laufende Projekte
* [ ] H W 99 11 Energiearbeit: 2h Labor, 3 Haufen: (Behalten) Verkaufen Verschenken Entsorgen
* [ ] H W 90 08 Keller säubern
* [ ] J W 90 08 link:../prv/entscheidungsfindung-mentale-modelle.adoc[MM]
* [ ] H W 60 Liste jeder Raum 60min, Entsorgen-Verkaufen-Behalten.
* [ ] GdW 30 09 KKasse wechseln
* [ ] Hdw 30 03 Isomatte (+ Luftbett) auf Dichtigkeit prüfen
* [ ] JdW 60 03 Office: Script in kh: Copy smb; ocr +  guess Name! Enum mit bekannten Absendern

=== Irgendwann
* [ ] Gdw TB 01 Harte Matratze im eigenen Haus oder kaufen.
* [ ] Gw  60 03 Skript, wie man das Wissen und Dateinamen aus doc & office grepfähig machen kann, vielleicht mit t d <search> (oder o)
* [ ] Jdw 99 03 Mein Miro https://miro.com/app/board/o9J_lruDyUo=/ umziehen nach board.drawio.svg  ?Daraus OKRs generieren? 3, 5, 15 Jahres Plan?

* [ ] FDW 30 03 ?Jens Rabe monatlich https://aktienkannjeder.de/?utm_source=mail&utm_medium=newsletter&utm_campaign=aktienkannjeder
* [R] F W 99 01 Andree de B Aufstellung verstehen, Pflege-Routine erarbeiten
* [ ] F W 45 03 Outcome Frame Dietmar Vermietet. Vorteile beachten.
