include::{root}/.inc/include.adoc[]

= Flow! Summit 2023

== Timo Janisch: Bewusst mit Traumata umgehen
* Tapping technik

== Tim Taxis
* src https://my.younity.me/products/flow-summit-2023/categories/2152005607/posts/2164299978
flow! summit 2023

===  Hindernisse zum Aufwachen
1.) Wissen über Spiritualität
2.) Sprituelle Praxis

Das hier und jetzt ist vollkommen.
Wenn da quälende Gedanken oder Gefühle sind, sagst du NEIN zum hier und jetzt und zur Vollkommenheit 15:12

Wenn das Hier und Jetzt noch nicht als vollkommen erlebt wird, dann bist Du einfach noch nicht da. Wo bist du? In
Gedanken, in der Vorstellung, wie es zu sein hat.
Kümmere Dich nicht wie es sein soll, sondern öffne dich vollkommen für das, wie es ist. 15:38

Wenn Du also Nein zum Hier und Jetzt sagst, und dann eine spirituelle Praxis nutzt, gehst du raus aus dem Hier und Jetzt.
Du sagst zum Leben: Nein Du reichst mir nicht, Du bist nicht OK. Nun kann es sein das die Erfahrung, die Du machst,
angenehm ist, aber Du legst die auf das, was auch noch da ist (Dein Nein!) drauf, und das kommt irgendwann durch und
deshalb ist die schöne Erfahrung vergänglich. Hinzu kommt: *Wir kreieren eine weiter Identifikation!* Ich bin jetzt ein
... Meditierender, Yogalehrer ... Da ist jetzt der Alltag und da meine Praxis (wieder eine Trennung!)
Benutzt Du jedweilige Praxis *UM-ZU*: Wenn ich erst meine Praxis tue *DANN* bin ich entspannt.

Meine Empfehlung: *TUE-NICHTS*

Sei still (und wisse ich bin Gott), Sei innerlich unbewegt.
In der Stille wird es dann fürchterlich laut, wir tun so viel nur um das was wir als fürchterlich erahnen nicht erleben zu müssen.
Weil dort Gefühle auf uns warten die wir nicht wollen
Ich hatte einen harten Tag, jetzt möchte ich mich entspannt fühlen. Tue ich aber nicht. Das Hier und Jetzt ist vollkommen, deshalb
bist Du in Gedanken.
Wenn ein UM-ZU enthalten ist, ist es keine Liebe. Liebe ist ein Ja zum Leben, bevor es passiert.
*Es geht nicht darum Deine Gefühle zu ändern, sondern um die Beziehung zu Deinen Gefühlen*
Das Ego kommt damit nicht klar, dass man dafür nichts tun kann, aber mit jedem Tun entfernen wir uns vom Hier und Jetzt,
wir entfernen uns von uns selbst. Immer nur weil wir uns sagen, Du bist nicht OK.



== Tobias Becker, Partnerschaft

* ...brauchen wir um das Glück zu erfahren nichts anderes als stabile  Beziehungen zu führen und das beginnt immer in
der Beziehung zu deinen Eltern. Wenn Du lernst zu verzeihen, oder Danke zu sagen, oder bedingungslos zu lieben für
das was da ist, für Deine schlichte Existenz, ab dem Moment ist alles andere vergessen. Und die Beziehung die wir zu
anderem Menschen pflegen ist das Fundament unser Glück. 24:04
* ... siehe andere Menschen als Deine Spiegel

1. Bleibe immer in der Neukunden-Akquise, nie in die Bestandskunden Betreuung.
2. Gemeinsam Abenteuer und Lebensmomente sammeln. Das Leben ist wie eine Fahrt im Reisebus, da steigen Menschen ein,
   da steigen Menschen aus. Solange sie das gleiche Ziel haben, bleiben sie nebeneinander sitzen.
3. Alle elektronischen Gerte fliegen aus dem Schlafzimmer. Kein Telefone, Laptop, TV...
4. Finde das Charakter Tier deines Gegenübers
5. Werde selbst zu diesem idealen Partner


== Tom Mögele, Annehmen was ist
* Schmerz möchte auf etwas aufmerksam machen. Sei dankbar dafür und nimm es an, denn nichts was Jetzt ist, kann falsch sein
* Was möchtest der Schmerz mir zeigen?

=== Übung
* max. einmal pro 1/4 Jahr
* Wichtig alles ohne Ego,
  ** Schulterbreit, linker Arm hängen, rechte Hand hoch, leicht über der Schulter
dann an ein Thema denken, dass ihr gerade annehmen wollt, geht in das Thema rein und schaut euch nur das Thema an
und sagt: "Es  ist alles gut ich nehm das an", die Energie geht rein in die Hand, die Hand wird dann evtl. warm,
es löst sich auf.
Und wenn das nichts mehr kommt einfach die Hand runter nehmen.
Das Thema, was ihr euch dann ran holt, ist sehr stark Energie geladen, mit der Hand wird die aufgestaute Energie
aufgenommen und wieder dem Körper zugeführt. Dh. die Energie wird ausgeglichen.

* Buch: Das MINDFLOW Konzept: Wie Sie durch Nicht-Wollen und Nicht-Tun alles erreichen


== Alberto Villoldo
* Die Wale, Delfine und Menschen haben nicht das Todes programm nicht. Alle sind zu sterben, wenn das WEibchen nicht mehr Reproduktionsfählig ist. Bis auf die 3
* Der homo lumines, mit der Natur, nicht als Parasit
* Das N1 Experiment der Langlebigkeit. Wir leben in der 6. Großen Auslöschung sein ca. 15 Jahren. Die Chance die wir haben selbst dieser NEue mensch zu werden, der homo Lumines. Es geht alles sehr schnell, wir erleben das. Wir müssen zulassen das der alte homo sapiens und uns stirbt.
* Wagt den Quantensprung. Alles Loslassen was mit dem alten Mensch in Verbindung steht. Der Eroberer, der Ausnutzen, der Respektlose, dieser TEil muss sterben und diesen albtraum hinter uns lassen.
* Nimm dir eine Kerze und einen Stock, Lass alle Identitäten sterben. Blase deine Identität da rein und verbrenne den Stab
* Wisse was Du dir auf den Teller packst. Alles Grüne

== Alexander Mark
* Nimmst Du Dich und deinen Traum ernst? Glaubst Du daran das du es wert bist diesen Truam zu leben? Erfolgreich nehmen ihre Traum ernst.
* Spüren intuitiv bewusste erfolgentscheidungen
* Der Glaube an dich selbst stellt sich allmählich mit den Resultaten ein und du dardurch in eine richtig mächtige Aufwärtspirale katapultiert wirst.
* Jim Rohn, der nicht das Geld für Kekse von Pfadfindern hatte, die an seiner Tür klingelten
* Der Tag an dem eine 180° Grad Wende möglich ist. Was wäre notewendig damit du beginnnst? Bewust sein, das es notwendig ist erfloglreihc zu werden.
* Finde Energie in allem! Du bist wütend auf dich selbs? nutze diese Energie
* *In den Momenten der Wahrheit immer wieder eine Bewusste Erfolgsentscheidung treffen BEE*
* 1 Ausbildung abschließen,
* Du lebst Das Leben, das zu zuvor gedacht hast. Denk darüber mal nach. Bist Du mit Deinem Leben zufrieden? Oder glaubst Du das Du hier und da deine Gedanken verändern solltest?
* Um Deine Gedanken zu verändern brauchst Du dich nur für neue Gedanken zu entscheiden
* Erfolog ist letzendlich nichts anderes als eine Kette von bewußten Erfolgsentscheidungen
* Für die meisten Menschen ist das Leben eine Art Mischung
* Treffen wir doch in jedem Moment des Lebens eine Bewußte Erfolgsentscheidung. (Nur, was ist Erfolg? Was will ich eigentlich? Was ist mir im Leben das Wichtigste?)
* Was würde Dein Herz zum Singen bringen
* *Ein Ziel zu erreichen heißt, auf dem Weg der Mensch zu werden, der es erreichen kann*
* Zielfindungsmethoden
  ** 1 Schaufensterbummel: Suche nach Dingen die du Willst. Öffne Deine Augen, schaffe das Bewußtsein, zu sehen, was über das hinausgeht, was Du gerade tust. Öffne Deine Geist für Beziehungen und Fähigkeiten, die du bein anderen bewunderst. Schau auch Dich selbst genau an, wie würdest Du Dich gerne selbst sehen?
  ** 2 Listenmethode: Screib alles auf was dir in den Sinn kommt, Was möchtest du gerne in Deinem Leben sein? oder Tun? Sobald Du im Schreibflow bist, schreib einfach alles auf. Egal wie albern. Gehe die Liste immer wieder durch und grenze sie ein bis ein oder zwei punkte immer wieder auftauchen. DAnn hsst du ein Destilat
  ** 3 Der emotionalen Ansatz: Du konzentrierst dich 10min darauf glücklich zu sein. Was hast Du das letzte Mal gemacht, als Du dich so glücklihc gefühlt hast. Woran denkst Du? Es wird wahrschenlich der Bereich sein, in dem du beginnnen solltest Deine Ziele zu setzen. Nicht mit etwas was du glaubst tun zu solltest.
  ** 4 Frage und Antwort Methode 10min Timer, Bauchgefühl soll entscheiden! NIhc der Verstand
    *** Wie glücklihc willst du sein
    *** Wie geusnd willst du sein
    *** Wie wohlhaben willst du sein
    *** Wie willst Du ausssehen
    *** Was möchtest du haben
    *** Wohin willst du gerne gehen
    *** wers oll mit dir dort hingegehn
    *** wie willst du dihc gesundheitlich fühlen
    *** Was willst ud dir selbst oder andern beweisen
    *** was möchtest du tun
    *** wen willst du dabei haben
    *** was bereitet dir freude
    *** gibt es etwas auf das du dich besonnders freust?

Aufgeschriebene Träume sind ein Stück weit realer. Es ist wichtiger den Traum zu haben, als die Schritte zu erkennen.
  ** 5 Tagträumen: Sind der Anfang jeden Aufbruchs und können Dich zu einem freudvollen Leben führen. Sich Zeit nehmen um sich etwas vorzustellen, was noch nicht zu deinem LEben gehört ist kein Luxus sondern eine Notwendigkeit. Dein Tagtraum ist Dein erreichtes Ziel im Anfangsstadium. Deine Träuem zeugen von dem Mut Dinge zu erreichen, die andere für unerreichbar halten. *Wer seine Träume aufgibt, gibt auch die Hoffung auf* Tagträume sind eine Möglichkeit enen Blick auf dsa zu werfen, was man will.

* Auf dem Weg des Traumes gibt es immer wieder Dinge, die dich in Angst und Schrecken versetzen werden. Die Angst kann sich zu einer Mauer formen. Diese Mauer du durchbrechen ist möglich, in dem Du dir verdeutlichst, es ist gar nicht alles Neu, es gibt genug Parameter die Du schon kennst. Wenn Du über eine Schmale Brücke ohne Geländer gehst, bist du aber schonmal über einen schmalen Bürgersteig gegangen. Versuch jede Angst rutner zu brechen auf etwas was Du jeden Tag tust. (Pipi-Langstrumpf Methode)
 * Die BEE bringen Energie in Dein System und schaffen Enge (Ballon), entweder du explodierst und findest Dich auf einer höheren Ebene wieder oder du läßt energie ab, in dem Du Serien schaust, süßes isst oder rum surfst oder verzettelst dich, jede Ablenkung, alles was dir hilft, den inneren Druck, die Enge los zu werden.