include::{root}/.inc/include.adoc[]

= Partnerschaft

* src /home/dietmar/cloud/andi/Brigitte Koch-Kersten/CD-Abenteuer-Partnerschaft/Abenteuer_Partnerschaft.mp3

== Fragen

* Benennen Sie einen Veränderungswunsch, den Sie an ihren PartnerIn haben, der sich nicht erfüllt, obwohl sie
  ** es ihr/ihm das schon oft mitgeteilt haben.

* Welche Hoffnungen verbinden Sie damit das Ihr PartnerIn anders wäre? Was glauben Sie wäre dann leichter, schöner
  ** oder besser? Welches tiefer liegende Grundbedürfnis würde sich dann erfüllen?



== Schrift
* Zentrales Grundbedürfnis: Sich entfalten und entwickeln zu dürfen
* Häufige Beschwerde, das man sich nicht entfalten oder entwickeln kann.
* Zur Befriedigung braucht es die Erfahrung gewärmt, geliebt, getröstet und unterstützt zu werden. 
* Diese Bedürfnisse wurden in der Kindheit oft nicht erfüllt uns sollen jetzt mit diesem Partner erfüllt werden.

* Frage: Welche Sehnsucht hoffen Sie in der Phase des verliebt seins von Ihrem Partner erfüllt zu bekommen.

* Glücklich sein in einer Partnerschaft gelingt in dem Maße, wie Sie sich erlauben zwar ihre Sehnsüchte wahrzunehmen
  ** aber deren Erfüllung nicht von Ihrem PartnerIn abhängig zu machen. Anstatt diese Erfüllung vom PartnerIn zu erwarten
  ** ist das gesuchte Glücklichsein um ein vielfaches größer, wenn Sie die ersehnten Qualitäten, wie Liebe, Kraft,
  ** Geborgenheit in sich selbst entdecken.
* Wie kann das gelingen? -> Durch Arbeit: Selbsterforschungs-, Selbstbeachtungs-, und Selbstentwicklungsarbeit.
* Zentraler Gedanke: Das Unglücklich sein als Chance nutzen, sich selbst zu erforschen und ihrer Selbstliebe zu wachsen.
* Was wünsche ich mir, was ist meine Sehnsucht, wie kann ich selber diese Qualitäten finden, dich ich mir vom PartnerIn ersehne
  ** (Wie gefällt das? Für alles selbst verantwortlich zu sein? -> Enttäuschung)
* Wann ist eine Partnerschaft zu ende? Wenn die Belastung so schwer ist, dass Sie sich darin nicht mehr entwickeln können.
  ** Wenn man nicht mehr in Ruhe kommt mit sich selbst, weil man andauernd Attacken, Angriffe, schwierige Dinge vom Partner
  ** ertragen zu müssen.
* Sonst, nutzen Sie die Zeit sich selber zu entwickeln und befreien Sie sich von der selbst auferlegten Not.
* 17 Wenn die Frage aufkommt nach Trennung, eine Unentschlossenheit, dann findet die Beziehung noch statt, dann ist es 
  ** noch nicht der Zeitpunkt zum Gehen.
* 5 Schritte um in Selbstliebe zu wachsen
  ** Beachten Sie die Not in die Sie sich gegenseitig bringen. (Ärger, Wut, Enttäuschung)
  ** Diese Gefühle zulassen, ohne es auszuagieren, ohne es zwingend an den Partner heranzutragen, besonders dann, wenn
  ** es um die Gefühle geht, die mit den Sehnsüchten verbunden sind. Wahrnehmen welches Grundbedürfnis sich hinter dem
  ** Gefühl verbirgt, von dem Sie hoffen, es von Ihrem Partner erfüllt zu bekommen. Es geht dahinter meist um ein
  ** Grundbedürfnis, das viel älter ist als die Partnerschaft. Beispiel: 24 Einer will sich mitteilen, der andere will sich
  ** lieber zurückziehen. Oder: 27 Ich laufe dem Partner immer hinterher... Das Gefühl dahinter zulassen, danach kehrt
  ** innere Ruhe ein. Beziehungsmuster, die man in der Kindheit gelernt hat, werden in der Partnerschaft wiederholt.
  ** Der Partner löst diese Alten Gefühle aus, weil es so ähnlich ist, wie es früher war. Danach die Ruhe genießen
  ** aus der Erkenntnis, dass ich das schon alles in mir trage. Wenn man in diesem Zustand der Ruhe auf den PartnerIn
  ** zugeht, ist es wahrscheinlicher gehört zu werden. Man gerät sonst in Abwehr, wenn der PartnerIn sagt: Sei so...
  ** Das Bewußtsein, ich trage alle Anforderungen schon in mir, macht frei.
  ** Warum kann es sein, das man das nicht fühlen kann? Wenn in der Kindheit diese Sehnsüchte lange Zeit nicht erfüllt
  ** wurden, kann es zu einer Selbst Verneinung kommen, da das Kind die Eltern nicht anzweifeln kann. 41 Das Gefühl ich
  ** bin nicht richtig, löst existentielle Nöte aus. Man sucht Wege da nicht dran denken zu müssen. (Dissoziation)
  ** Man muss eine permanente Spannung aufrechterhalten, um solche Selbstzweifel von sich fernzuhalten. Es wird ein
  ** Partner gesucht, der es ermöglicht das Wiedererleben zu vermeiden, das ist die stärkste Motivation für eine
  ** Paar-Beziehung. "Titel: Liebe Dich selbst, und Du kann heiraten, wen Du willst."

== Zusammenfassung
Eine Partnerschaft ist eine Einladung, frühe aus der Kindheit stammende Lebensängste aufzulösen. Dazu ist es notwendig
das Unglücklichsein dazu zu nutzen, glücklicher zu werden, um sich darauf zu besinnen, welche Gefühle gehen in mir vor,
wenn ich mich an dieser oder jenen Stelle ärgere, ... Was ist das für eine innere Sehnsucht auf deren Erfüllung ich 
eigentlich hoffe, die aber immer nicht zustande kommt? Der Partner ist also immer ein Spiegel, in den ich schauen kann.
"... hier fühle ich mich ungeliebt... was sind da für Gefühle, diese Gefühle zuzulassen und sich selber liebevoll zu
beachten, anstatt zu erwarten, dass der Partner das macht."
1. Schritt: Ich nehme mich wahr.
2. Welches Gefühl ist da?
3. Gefühl Raum geben und ausfühlen.
4. Welche Sehnsucht wurde verletzt?
5. Brauche ich meinen PartnerIn dazu? Kann ich mir das nicht selber geben?
6. Frieden genießen
7. Wenn, nur im Frieden darüber mit dem Partner sprechen.

Alle Ängste, die man bis dahin aufgelöst hat, führt zu einer höheren Liebesfähigkeit sich selbst und damit auch
dem Partner gegenüber. Man wächst in der Liebesfähigkeit und das hebt die Beziehung auf ein höheres Niveau.

Von dem Partner geht keine existenzielle Bedrohung aus, auch wenn es sich so anfühlt. Und sie werden feststellen, 
dass er das nie konnte.

Der Gewinn ist, frei sein, Autonomie, Lebensfreude, Lebenslust, Kreativität und Glück. Nicht weil der Partner sich
geändert hat, sondern, weil man sich das, was man sich ersehnt, in sich selber als Qualität gefunden hat. Häufig 
ändert sich dann der Partner dann in die Richtung wie man es gerne hätte. (Weil das Ziehen in die Richtung aufhört
und damit der Widerstand in die Richtung aufhören kann)

62 Wenn Sie keine Hoffnung haben, die Herausforderungen, die Ihnen Ihre Partnerschaft zur Entwicklung bietet 
nutzen zu können, können Sie prüfen, ob es für Sie richtig anfühlt sich zu trennen.
