= Praktische Selbstmotivation: 22 einfache Zaubertricks für spürbar mehr Motivation

* src Kindle Buch
* Bonus: Die 163 besten Motivationssprüche (German Edition)
* Jan Höpker
* Wednesday August 28, 2019, gekauft 2019-06-21


== 3 Motoren
* Gewohnheiten (gedankenlos)
* Willenskraft (aus Vernunft)
* Motivation (innerer Antrieb)

== Unzufriedenheit
* Unzufriedenheit ist die größte Motivation
  ** Unzufriedenheit kann nur dann zu Motivation führen, wenn ein Weg erkennbar ist.
* Wer nicht weiß, was er konkret tun kann, um aus seiner Situation zu entkommen, wird nicht motiviert sein. Er wird dauerhaft unzufrieden bleiben oder in Panik geraten.

== Gefühle
* Unsere Gefühle haben die Aufgabe, uns einen Weg zu zeigen.
* Unsere Gefühle sind wie ein Kompass. Mit allem, was wir tun, verfolgen wir im Grunde eines von nur zwei Zielen: Das eine Ziel besteht darin, Freude zu spüren und das andere Ziel ist die Vermeidung von Schmerzen.

== Erhaltung
* Wenn man sich Motivation für eine bestimmte Tätigkeit schaffen und erhalten möchte, sollte man daher unbedingt darauf achten, möglichst keine negativen Erfahrungen zu machen.
* Sobald der genaue Lösungsweg von oben diktiert wird, löst sich intrinsische Motivation in Luft auf. Menschen wollen nicht ferngesteuert werden.
* Motivierte Menschen entfernen die Auslöser für Ablenkungen
* Die Kunst bei der Selbstmotivation besteht darin, die Motivation für die zu erledigende Aufgabe zu verstärken und die Motivation für Ablenkungen zu reduzieren.
* Mein Problem ist, dass das Schreiben nicht die einzige Sache ist, für die ich motiviert bin.
* Sobald eine Sache in meinem Blickfeld auftaucht, die mit irgendetwas zu tun hat, wofür ich motiviert bin, dann drängt sich mir diese Sache penetrant in mein Bewusstsein.
* Das gravierendste Problem mit den ständigen Ablenkungen ist nicht, dass sie uns sehr viel Zeit kosten. Das Problem ist, dass sie unsere Motivation zerstören. Vereinfacht gesprochen möchte unser Gehirn, dass unsere Taten mit unserer inneren Einstellung übereinstimmen. Um das zu erreichen, macht das Gehirn nicht davor halt, unsere innere Einstellung an das anzupassen, was wir tatsächlich tun. Wenn mein Blatt Papier nach Stunden immer noch leer ist, dann wird mein Gehirn meine innere Einstellung dem Schreiben gegenüber an dieses Verhalten anpassen. Ich werde das Schreiben doof finden, und ich werde nach einiger Zeit sogar glauben, dass ich das Schreiben schon immer doof fand. Erinnerungen werden nämlich ebenfalls nachträglich angepasst. Eine interessante Lektüre zu diesem Thema ist das Buch „Aussetzer“ von Daniel Schacter, einem US-amerikanischen Psychologen.
* Ablenkungen sorgen also nicht nur dafür, dass man länger braucht, um die Sache zu erledigen. Ablenkungen könnten auf Dauer sogar dafür sorgen, dass die Motivation komplett verloren geht.
* Wenn du eine bestimmte Aufgabe zu erledigen hast, solltest du dich so wenigen Auslösern für Ablenkungen aussetzen, wie nur möglich.

== Voraussetzungen für intrinsische Motivation
* Perfektionierung geht es um Wachstum.
* Sinnerfüllung geht es darum, dass wir unsere Werte leben können.
* Es gibt nur eine Möglichkeit, diesen Ablenkungen zu entkommen: Die Auslöser dürfen nicht im Blickfeld sein. Man muss sich einen Auslöser-armen Ort schaffen.

== Routinen
* Routinen können uns dabei helfen, regelmäßig unliebsame Aufgaben zu erledigen, ohne uns jedes Mal aufs Neue dazu überwinden zu müssen.
* Meine Routine ist vor allem deswegen so erfolgreich, weil ich sie direkt an eine bereits bestehende Routine angehängt habe: das Frühstück.
* Wenn du dich mit einer bestimmten regelmäßigen Aufgabe schwertust, dann integriere diese Aufgabe in eine bereits bestehende Routine. Die Zeit nach dem Frühstück ist noch aus einem anderen Grund ideal: Zu dieser Tageszeit steht uns noch ausreichend Willenskraft zur Verfügung.

== Scheitern
* Wichtig ist, dass du dir selbst erlaubst, nach dem ersten Satz oder dem halben Kilometer aufzuhören, ohne von dir selbst enttäuscht zu sein.
* Worauf es also ankommt, ist das Anfangen. Je weniger man sich selbst unter Druck setzt, umso einfacher ist das Anfangen.

== Negatives Unterbewußtsein
* Interessant ist, dass das Gehirn eine Aufgabe als erledigt betrachtet, wenn man sie auf eine To-do-Liste schreibt.
* Wenn du für eine bestimmte Tätigkeit motiviert sein möchtest, dann solltest du vorher möglichst keine anderen Tätigkeiten beginnen, ohne diese zu beenden. Beende außerdem alle Aufgaben, die du schnell beenden kannst, bevor du mit der Tätigkeit beginnst, für die du motiviert sein möchtest. Schreibe alle angefangenen Tätigkeiten, die du nicht schnell noch beenden kannst, auf eine To-do-Liste. Wenn du all das tust, wird dein Gehirn dich mit demotivierenden Gedanken verschonen.
* Achte darauf, nicht negativ über deine Aufgabe zu sprechen. Verwende positive Wörter. Meide auch Mitmenschen, die negativ über deine Aufgaben sprechen. Wenn du in der Bibliothek lernst, stell dich in der Pause nicht zu den Leuten, die darüber schimpfen, wie sehr sie vom Lernen genervt sind.

== Aussprache
Sage nicht ich muss arbeiten, sondern ich will arbeiten oder zumindest ich werde arbeiten.

== Ziele
* Es gibt mindestens zwei sehr gute Gründe dafür, sich im Leben eigene Ziele zu setzen:
* Selbstbestimmung und Effektivität.

== SMART ...
* Der Nachteil von S.M.A.R.T. Zielen ist, dass sie auf Disziplin und Willenskraft aufbauen, aber nicht auf Motivation.
* denn Willenskraft steht vielen Menschen nach ihrem Feierabend einfach nicht mehr in brauchbaren Mengen zur Verfügung.
* Zukunftsvision zu beginnen: einem klaren Bild davon, wo man hin möchte.
* Die Zukunftsvision hat die Aufgabe, den ganzen Prozess mit motivierender Energie zu versorgen.

== Zukunftsvorstellung bauen für:
* für die körperliche und geistige Verfassung (Gesundheit),
* für den Beruf beziehungsweise die Lebensaufgabe
* für die sozialen Beziehungen.
* Übertreibe etwas: Wer sich das Ziel gesetzt hat, monatlich 10.000 Euro zu verdienen, kommt auf ganz andere Ideen, als jemand, der schon mit 1.000 Euro zufrieden ist.

== Etc
Einige Experten empfehlen sogar, dass man sich seine Ziele täglich neu aufschreibt, um sie sich richtig intensiv einzuprägen.
Wenn du dich zum Lernen motivieren möchtest, geh in die Bibliothek, wo du von anderen Lernern umgeben sein wirst. Zum Lernen ins Schwimmbad zu gehen ist keine gute Idee.
Erledige Aufgaben, die viel Willenskraft benötigen, immer möglichst früh am Tag. Am besten sofort am Morgen. Wenn du dir klar machst, dass deine Willenskraft morgens am stärksten ist, wirst du auch merken, dass das Aufschieben unangenehmer Tätigkeiten oft purer Selbstbetrug ist.


== Wie können wir diese Welt zu einem besseren Ort machen?
* „Tue etwas, das wertvoll ist“
* Was wir für andere Menschen tun können.
* verschiedene Dinge ausprobieren,
* Fähigkeiten aneignen, die in vielen Bereichen gefragt sind.
* wo man mit den eigenen Fähigkeiten am meisten ausrichten kann.
* Tagtraum, bei dem man die zu erledigende Aufgabe in Gedanken durchspielt.
* Die Vorstellung, bereits am Ziel zu sein, führt zur Entspannung. Die Motivation sinkt also.

== Zitate
* Ich zahle nicht gute Löhne, weil ich viel Geld habe. Ich habe viel Geld, weil ich gute Löhne zahle. (Robert Bosch)
* Wenn du fliegen willst, musst du die Sachen loslassen, die dich runterziehen. (Toni Morrison)
* Die ehrlichsten Menschen haben nicht viele Freunde.
* Erst nachdem wir alles verloren haben, haben wir die Freiheit alles zu tun. (Tyler Durden)
* Alles, was du sagst, sollte wahr sein. Aber nicht alles, was wahr ist, solltest du auch sagen. (Voltaire)
* Umgib dich mit Leuten, die besser sind als du. (Warren Buffett)
* Menschen wurden erschaffen, um geliebt zu werden. Dinge wurden erschaffen, um benutzt zu werden. Der Grund warum sich die Welt im Chaos befindet ist, weil Dinge geliebt und Menschen benutzt werden. (Dalai Lama)
* Nutze die Talente, die du hast. Die Wälder wären sehr still, wenn nur die begabtesten Vögel singen würden. (Henry van Dyke)
* Der sicherste Weg zum Erfolg ist immer, es doch noch einmal zu versuchen. (Thomas Edison)
* Unser Leben ist viel schwerer, als das unserer Vorfahren, weil wir uns so viele Dinge anschaffen, die uns das Leben erleichtern. (Gabriel Laub)












