include::{root}/.inc/includeDaily.adoc[]

= Tantra Seminar

//-----BEGIN MESSAGE-----
U8Kvwo7CisK9w4TCs8KewqXDosKsw4XDhm5zwpDCl8OZwr/DoMOUwrXDmnHC
ocWHwrfCpMKYw4TDoGXCr8Wuw4PCisOBw5XCucKhwqTDnsKnfcKBxLrCtcKc
bMK/w4PDq8ObwrHDk37CocOYwqfCqVx/w4fCrcK7wp/Ck8Ocw5bDj8K8wpjC
p8KmesKzw43DhcKww5V4wo3CrsOYw5nCs8OPwrbCu8OXxYDCpMKYw4TDpHFp
wrPDhcOPw5rCg8KVwqXCn8OrwqLDhMOEw4zCrsOieMKNwq7DisOOwrnDmcOF
bcOYwrLCpVDEu8OUwqrCu8KfwqHDn8OZw4/CuT1jwpnCjMK2w5nDnWnDhcK6
w6HCv8Opw47Cv8OawrbCu21OS23CnMKSwpvCuMOkwrPDj8Ofw4jCucKnwq7D
p8KgW8KLwoTCj8OZwrrDlMK/w6nDlMS0w47CtsK5woPCr8K2wqLDmcKeZcKj
xZbCucOYw5LCg8OAwqjCrcOzwp7Cv2vCjmnCvMOBw5vDgcOfw49wwrLCv8K8
w5fCqcKvUMKOwpLChsK3w6zCusOPw5XDiMK+U8S1w5vCnsK/a8KOacWMwq7D
ksOMw5jDksK8wofDg8Kuw5bCrcKmwqLDhMOgT3PCksKWw5PDm8KDwqPCo8Kr
w6LCrcOLw4bDlmnDgMKtw5/DgMOsw5NawpFxwqLDi8K2YcKRw4HDnsKqwrDD
l8K/wpbCjcKlw4LCnMKlw6XCnnHCosOGwrXDlcKzw5LDiMKjwobCo8OWwrTC
uMOIwrJhwpHDlMOlwr/CssOXwrnDj8ObbVpwdsKZwoDDg8OWw5LCrcOjxLDD
ocOUw5xwesKHwqHCv8OMwrLCu8KZw4/CksKpwq7DpHHCucOTw4nCtcKhwqHD
nsKiw4XCjcKEwp3DkcK6w6HDjMOYwobCucOaw4Vtw47CqcKqwp5/w4jCtMK7
w6XDgcOTw5LDj3Bbwp3DmlnCtsOUwoTCt8OZwq/DlcOOwpfDoMOFw5RxwqDD
iMK8YcKbw47Dn8Kywq7DoHHDl8OixYJ5PUPCg0PCjsKewoTCkMOcwrvDoMON
w5jDmFrCs8OGwrvDisKswqpQwozCsGXCi8OXwrjDlcOZw4jCucKXwq7Dp8Kg
w4TDlcOZwqzDmFbDhsOJw6XDj3DCh3F6wqFkwpTCk8OHw5fCrsKtw5dbwrbD
lsORwrfClMKmwplmwo/CgcKrwrXDmcKxw5Fkw4rDjsK5w53Csm3Cg3F/UMKs
w5PCs8K3fMKkw5LDjsOOw4TCnFnCpndxwqfDlsKqw6VWdw==