include::{root}/.inc/includeDaily.adoc[]

= Lizenzen / Codes / Keys

* VMWare 17 Pro, Eagle, Enterprise Architekt, Intellij, Matlab, Microsoft, Total Commander

//-----BEGIN MESSAGE-----
U8Kvwo7CisKNwrnCvcKqwprDq8KeccK4w5PCu8Obwr/DocK7w6vDj8K/w5Vx
fsKaZMKRwqLDjsKSwpHCssOYwrbDnsOWw5DCtVPChcOiwpzCtsOPw5fCrnp2
wo3CqsOpw5XCtMOcwrzDgcOWwqfCqcKcxZvDpcK4wq7DnsKLworCvcOVwr/C
l8Kuw5zCrXHCrMOJw4LCqmzDh8KgwqzCvcKIwpTCl8Kdwrt0wpJdwo/CqnXC
mcODfsKiwrrCsMKqeGbDkcKOwqbCosKlU8KabMKuwr3Dq8OPw4bDiMOFwrbD
ksKyYXzDiMOfwq7CvcKsccKbd23CjXBZwr7CmsK4w43DiWnCvMK1w6fCv8Ol
w5lawpFxw4LDkcK4wqbCon/DlcKxwrjDp8K1wpnDncOVwr/CncKew5zCrcKA
w43DhcKrw5/CvsKcw43DpsOMw4TDnsKywr/DiHPCpsKRw4bDnsKqU3xbdMKq
wqBweMKnw63CnsODw5HDlsKyw6PCscKNwpvDqcOJwrjDkMOFwrLDhsK4S13C
jMKfclPCt8KSworDqMKpwoJlbcKpfsKHwpHCkXnCocKEwrHCh8KowpfCtMKc
fsKOwpp6woddwpHCtcKGe8KzfsKywqXCscKDYMKIw4zChcKYwo7CmcKewrLC
k8KawpLDgsKuwpbClMKSfcOgTm5dwozCn09Twq/CjsKKwrbDkcOEwpjCpcOl
wqLCu2vCkXbCnXl3woTCl8K0wrHDlMK2wofCg8KFwohxw4jDgGXClcObwrTD
j8Obw5bCtVPChMOewrLCi8KBwpt8wqnCgMKlwofDjsKewpXCtMKWesK4wpN0
wojCj8KffcKBw4vCmMKswprClcKnaXrDiWbCncKlwrbCjMKnVsKXesOMw5nC
tcOZccKbw4TCscKman/CtsKuwq7DpsK+w4vDn8KDwqrClMKbw57CpVvCi8KE
wpXDmcKvw5LDiMOqw4twwrLCtsOGwp1kdmnCk8KmdnvCn8KUw4DCn8KywpJg
csK+wpHCh8K2wpHCnMK1wpvDgcKpwqTCnMKFw4DChcKnwpDCjHlowqLCpU92
wp9+wpd3bcKNcFnDhsKaw4XDjcOFwqt6dsKNwpvDosOawrnDncK6wrLDlcK5
wq/Cl8OSw6XCqMKxw57FjcOdw6DDiMK8U2rCrm3CicKXwpF5wqLCgMKgwpPC
pMKZwoLCn8KGfcKQe3hmwpjCpHJ7wqXChsKhwqJtWnB2wpnChsK6w4TDlsK4
w6PCu8OTw47CgcKQcMK+wrrCu8KaZHTCh8KRw4jCjXbCqMKDw4HCpMKnfcKF
e8K7wpDCnMKOwrF7wrfClsKjwofCusKdwoTCn8KlV8KNZMKQwpbDhcObwqjC
rsKSwqHDnMOcw4nCtcKmwqzDosKowr/DgsOQacKifMKeworCscKGwprCnsKo
wo/CvHHCmsKHwqfCqcKXdsOGwpjCoMK1wpl9e3vCu8KKwqfCjsKuwpHCtsKd
w4VkwqHChsKnw5DCv37Ck2TCp8Ssw5HCksKUwq/DmMK6w43DksKDwqB2c8KZ
woPClcKawpjCl8KdwoXCv8Kgw4HCn33CvsKFwp/Cl8KPbmfCksOLwpvCjcKf
wp7CrsOEwrvCnT1jwpnCiMK3w4fDjcKsw5Vswp/CisKowp9wwqjCv8Kxw5XC
qcKiUMKxwqvCksKXwrR+wrXCuMKZwqHCg2bCq8KSwp7Cp8K6dsK3wpDCt8Kk
wqrCk8Kdwp7CqcKUwpZOa1DCrsOYwqvCssOVwrbCisKfwpPCgWxZwr3CosK2
w5XDkcKqw6Jsw4PCp8KXwprCiMKqwofCl8KQwpLCh2bCtcK4csKBwqrCpcKw
w4XCkMKdwoN/w4HCin7CpcK6woHCu8Kdd8KEwpfCvcK5w5VxfsKTZMKnxKzD
kcKSen3CqcKBw5rCjcKVwp5nwovDiWbCicK6wrV/wrZ5w4TCpcOJwp3CgsKU
wpTClMKceMKTXcKsw4nCl8KMwqhbwpTCjcK6wrnCoVnCqmlxw4fFoMK7wpDC
scKjwo7Cq8KWcMKdwqLCncKawpJuZsKTwqrCkMKCwp/ChcKgw4XCmsKCYHHC
snvCmMKawpHCosKnwqLCn8KQwoHCkHDCvsK6wrvCg3VxUMKvw6TCtGnDmMWN
w5zCjcOHwrHCplnCusKsw4bDlMKEwpfDn8OAw5LCvMOmw5XCu8KHwp/Cj8Kc
wod0XcKqw4jCksKfwqR+wrzCsMKWwol7ZsK9ccKJwrXCunbDhsKgwqbCrsOQ
cFpxW1fCoMKBYcKDw5PDk8K3wrbDocK/w4/DpsKDwoFjQ8OCwqHDg8KBwrDC
ssOqwrHDm8OUw6rDicK4w5PFjcOAw5bCqcKtUMOLw5PCusK9w5fDhcKkwo3C
tsKAZGvCrGbChcKWwpXCgcKkecKlwrLDkMK/woPClMKbf8KYfHRdwpHCqn1/
wqpbdMKqwqBwwofCqMOtwprCvcKBwqfCuMOdwrnDjsOIw5vDi8OCcXttwqXC
rcKvxJTDkcOYwq7CtcOXccOfw5vDl8K1wqVZw5zCpcOAw5bDiHjDoMK+w5zD
hMOcw4nDhMKWwr3CrsOFwrPCs1/DksOhwqvCvcOpwrLDnMOSwpLDhMKiwq3D
msKlfsOEw5PCtsOdwq3Dm8K+w5zDmH3DksK2w4bDgsKjwph5wq3CtcKSwo3C
oMKcwq/Dhg==